/* Visible settings shared by single-task tools and the novel editor. */
window.Creation=(()=>{
 const labels={image_unet:'千问图像模型 · GGUF',image_clip:'图像文本编码器',image_vae:'图像 VAE',video_unet:'Wan 2.2 5B 模型',video_clip:'视频文本编码器',video_vae:'视频 VAE',tts_dir:'IndexTTS 2.5 模型目录',asr_dir:'Qwen3-ASR 模型目录',align_dir:'Qwen3 对齐模型目录'};
 const schema={image:[['width','图像宽度',256,1920,16],['height','图像高度',256,1920,16],['steps','图像步数',1,60,1],['seed','图像随机种子',0,2147483647,1],['cfg','提示词引导 CFG',1,10,.1]],motion:[['width','动态镜头宽度',256,1920,32],['height','动态镜头高度',256,1920,32],['frames','动态帧数（4n+1）',17,81,4],['fps','动态镜头帧率',8,30,1],['steps','动态生成步数',4,40,1],['seed','动态随机种子',0,2147483647,1]],output:[['width','成片宽度',256,1920,2],['height','成片高度',256,1920,2],['fps','成片帧率',8,30,1],['subtitle_size','字幕字号',12,48,1]],voice:[['reference','本地参考音色'],['emotion','本地情感'],['intensity','本地情感强度',0,.8,.05],['speed','语速（大于 1 更快）',.5,2,.05],['online_voice','在线音色 ID']],story:[['local_url','本机编剧接口 Base URL'],['local_model','本机编剧模型名称']]};
 const titles={image:'插画参数',motion:'动态镜头参数',output:'最终成片参数',voice:'默认旁白与音色',models:'本地模型组合',story:'本地小说编剧（可选）'};
 const voiceAdvanced=[['duration_factor','合成节奏（小于 1 稍紧凑）',.8,1.2,.05],['pitch_semitones','音高微调（半音）',-3,3,.1],['formant_shift','共鸣明亮度（实验微调）',.9,1.1,.01],['prosody_reference','表达参考（独立语气）'],['prosody_strength','表达参考强度',0,1,.05]];
 const qwenSpeakers=['Vivian','Serena','Uncle_Fu','Dylan','Eric','Ryan','Aiden','Ono_Anna','Sohee'];
 const qwenLanguages=[['Chinese','中文'],['English','英语'],['Japanese','日语'],['Korean','韩语'],['German','德语'],['French','法语'],['Russian','俄语'],['Portuguese','葡萄牙语'],['Spanish','西班牙语'],['Italian','意大利语'],['Auto','自动识别']];
 const voiceFallback={engine:'index-tts',qwen_speaker:'Vivian',qwen_instruct:'',qwen_ref_text:'',qwen_language:'Chinese',qwen_seed:42,prosody_reference:'',pitch_semitones:0};
 const engineOptions=[['index-tts','IndexTTS · 原版参考克隆'],['qwen3-custom','Qwen3-TTS · 现成声线'],['qwen3-design','Qwen3-TTS · 声音设计'],['qwen3-clone','Qwen3-TTS · 声音克隆']];
 const engineNotes={'index-tts':'IndexTTS 使用参考声音克隆音色，可通过情感或独立表达参考控制语气。','qwen3-custom':'Qwen 使用现成声线和表达要求生成声音；参考录音仅供试听，不参与克隆。','qwen3-design':'先用声音描述生成试听，再从成功任务“保存为固定角色音色”。设计结果需固定成克隆参考后用于多镜头角色。','qwen3-clone':'Qwen 根据参考录音克隆声音。参考原文留空时只提取音色向量；填写与录音一致的原文可提供更多克隆信息。此模式不使用表达描述。'};
 schema.voice.unshift(['engine','本地配音引擎']);schema.voice.push(['qwen_speaker','Qwen 现成声线'],['qwen_instruct','Qwen 声音 / 表达描述（最多 500 字）'],['qwen_ref_text','Qwen 参考录音原文（可选）'],['qwen_language','Qwen 语言'],['qwen_seed','Qwen 随机种子',0,2147483647,1]);
 schema.image.unshift(['engine','本地图像引擎']);schema.motion.unshift(['engine','本地动态镜头引擎']);
 const visualFallback={image:'qwen-image-2512',motion:'wan2.2-5b'},visualNames={'qwen-image-2512':'Qwen-Image 2512 · 原有插画','flux2-klein-4b':'FLUX.2 klein 4B · 参考图编辑','wan2.2-5b':'Wan2.2 5B · 原有动态镜头','wan2.2-a14b':'Wan2.2 A14B · 图生视频'};
 const visualCache={image:new Map(),motion:new Map()};let inventory,config;const hosts=()=>[...document.querySelectorAll('[data-creation]')];
 const visualProfiles=group=>inventory?.[group+'_engines']||[];
 async function api(path,data){const r=await fetch(path,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d}
 function select(options,value){const s=document.createElement('select');for(const [v,t]of options){const o=document.createElement('option');o.value=v;o.textContent=t;s.append(o)}if(!options.some(([v])=>v===value)){const o=document.createElement('option');o.value=value;o.textContent=value||'未选择';s.append(o)}s.value=value;return s}
 function field(group,key,title,lo,hi,step){const l=document.createElement('label');l.textContent=key==='reference'?'参考声音 / Qwen 试听样本':title;let input,value=config[group][key];if(value===undefined&&group==='voice')value=voiceFallback[key]??1;
  if(group==='models'&&inventory.choices[key])input=select(inventory.choices[key].map(x=>[x,x]),value);
  else if(key==='reference')input=select(inventory.voices.map(v=>[v.path,v.name]),value);
  else if(key==='prosody_reference')input=select([['','按情感控制'],...inventory.voices.map(v=>[v.path,v.name])],value);
  else if(key==='emotion')input=select(inventory.emotions.map(x=>[x,x]),value);
  else if(key==='engine'&&group==='voice')input=select(engineOptions,value);
  else if(key==='engine'&&visualFallback[group]){value=value||visualFallback[group];const rows=visualProfiles(group);input=select(rows.length?rows.map(row=>[row.id,row.name+(row.ready?'':' · 文件未齐')]):[[value,visualNames[value]||value]],value);input.dataset.previousEngine=value;}
  else if(key==='qwen_speaker')input=select(qwenSpeakers.map(name=>[name,name]),value);
  else if(key==='qwen_language')input=select(qwenLanguages,value);
  else if(key==='qwen_instruct'){input=document.createElement('textarea');input.value=value;input.maxLength=500;input.rows=3;input.placeholder='例如：冷静清晰地解说，语气自然，减少夸张起伏。'}
  else if(key==='qwen_ref_text'){input=document.createElement('textarea');input.value=value;input.maxLength=2000;input.rows=3;input.placeholder='填写参考录音实际说出的内容，不是本次配音台词。';}
  else{input=document.createElement('input');input.type=lo===undefined?'text':'number';input.value=value;if(lo!==undefined){input.min=lo;input.max=hi;input.step=step}}
  input.dataset.group=group;input.dataset.key=key;input.id='c-'+group+'-'+key;l.htmlFor=input.id;l.append(input);return l;
 }
 function voiceTools(box){const wrapper=document.createElement('div');wrapper.className='reference-tools';box.append(wrapper);box=wrapper;const upload=document.createElement('input');upload.type='file';upload.accept='.wav,.mp3,.m4a,.flac';upload.setAttribute('aria-label','上传参考音色');box.append(upload);const b=document.createElement('button');b.textContent='保存参考音色';const status=document.createElement('p');status.className='small';b.onclick=async()=>{try{if(!upload.files[0])throw Error('请先选择音频文件');b.disabled=true;const f=upload.files[0];if(f.size>12*1024*1024)throw Error('音频不能超过 12 MB');const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(f)});const d=await api('/api/voices',{name:f.name,base64});const newVoice={name:d.name,path:d.path};inventory.voices.push(newVoice);document.querySelectorAll('select[data-key="reference"]').forEach(s=>{const o=document.createElement('option');o.value=d.path;o.textContent=d.name;s.append(o);s.value=d.path});document.querySelectorAll('select[data-key="prosody_reference"]').forEach(s=>s.append(new Option(d.name,d.path)));document.dispatchEvent(new CustomEvent('voices-updated'));status.textContent=d.message}catch(e){status.textContent=e.message}finally{b.disabled=false}};box.append(b,status);
 const preview=document.createElement('button');preview.textContent='试听所选参考音色';preview.className='secondary';const audio=document.createElement('audio');audio.controls=true;audio.className='voice-preview';audio.hidden=true;preview.onclick=()=>{const input=document.querySelector('[data-group="voice"][data-key="reference"]');if(input){audio.src='/api/voice-preview?name='+encodeURIComponent(input.value.split(/[\\/]/).pop());audio.hidden=false;audio.play().catch(()=>{})}};box.append(preview,audio);
 }
 function render(){for(const host of hosts()){host.replaceChildren();for(const group of host.dataset.creation.split(',')){const box=document.createElement('fieldset');box.className='control-group';const legend=document.createElement('legend');legend.textContent=titles[group];box.append(legend);
 if(['image','motion','output'].includes(group)){const preset=document.createElement('select');preset.setAttribute('aria-label',titles[group]+'尺寸预设');const sizes=group==='motion'?[[512,288],[288,512],[768,448],[448,768]]:group==='image'?[[1024,576],[576,1024],[768,768],[1280,720]]:[[1280,720],[720,1280],[1920,1080],[1080,1920]];preset.append(new Option('选择尺寸预设（下面可自定义）',''));for(const [w,h]of sizes)preset.append(new Option(`${w} × ${h} ${w>h?'横屏':w<h?'竖屏':'方形'}`,`${w},${h}`));preset.onchange=()=>{if(preset.value){const [w,h]=preset.value.split(',');box.querySelector('[data-key=width]').value=w;box.querySelector('[data-key=height]').value=h}};box.append(preset)}
 const grid=document.createElement('div');grid.className='control-grid';for(const row of group==='models'?Object.entries(labels).map(([k,v])=>[k,v]):schema[group])grid.append(field(group,...row));box.append(grid);
 if(group==='voice'){const details=document.createElement('details'),summary=document.createElement('summary'),advanced=document.createElement('div'),hint=document.createElement('p');summary.textContent='高级调音 · 共鸣默认 1 保留原声，小幅改动需试听';advanced.className='control-grid';for(const row of voiceAdvanced)advanced.append(field(group,...row));hint.className='small prosody-note';hint.textContent='表达参考只提供语气，音色仍来自上方参考声音。选中表达参考后，情感与情感强度不生效；选择“按情感控制”可恢复。';details.append(summary,advanced,hint);box.append(details)}
 const note=document.createElement('p');note.className='small';note.textContent={image:'引擎仅用于本地生成。切换时会采用该引擎建议参数；切回可恢复本页原参数。在线请求仍使用在线接口设置，并携带这里的尺寸。',motion:'本地时长约为帧数 ÷ 帧率。切换引擎会采用建议参数；切回可恢复本页原参数。在线视频按在线接口设置请求 4 秒。',output:'成片尺寸用于最终合成；放大输出不会增加生成素材细节。白板竖屏会保留原画比例并补边。',voice:'建议 5–15 秒清晰单人参考音频。情感只用于本地；在线使用音色 ID 和语速，不上传参考音频。上传最多保留前 30 秒。',models:'这里保留原有 Qwen / Wan 5B 工作流的可选组件。FLUX 使用固定组件；A14B 的高低噪声模型与 VAE 固定，文本编码器沿用视频设置。新引擎清单见上方。',story:'本地 AI 编剧通过本机模型生成分镜；安装 Ollama 后可用工作台目录的 Start.cmd 启动。也可直接让 Codex 写稿。编剧与生图、配音共用显卡，请依次运行；完成后自动释放编剧模型。原文分段保留为不调用 AI 的选项。'}[group]||'';box.append(note);if(group==='voice')voiceTools(box);if(group==='story'){const state=document.createElement('p');state.textContent='正在检查本地编剧服务…';box.append(state);api('/api/story/status').then(d=>state.textContent=d.message).catch(()=>state.textContent='无法检查编剧服务，请刷新页面。')}host.append(box)} }
  updateEmotionMode();updateVisualEngines();
 }
 function updateVisualEngines(){for(const group of ['image','motion']){const input=document.querySelector('[data-group="'+group+'"][data-key="engine"]');if(!input)continue;const box=input.closest('.control-group'),profile=visualProfiles(group).find(row=>row.id===input.value);if(group==='image'){for(const key of ['steps','cfg']){const field=box.querySelector('[data-key='+key+']');field.readOnly=input.value==='flux2-klein-4b';field.title=field.readOnly?'FLUX.2 klein 蒸馏版固定使用 4 步 / CFG 1':''}}let note=box.querySelector('.visual-engine-status');if(!note){note=document.createElement('p');note.className='small visual-engine-status';note.setAttribute('role','status');box.append(note)}note.textContent=profile?(profile.ready?'组件文件齐全，生成效果仍需实际试图。':'组件尚未齐全：'+profile.components.filter(row=>!row.exists).map(row=>row.name).join('、'))+(input.value==='flux2-klein-4b'?' FLUX 蒸馏版固定 4 步 / CFG 1，支持最多 4 张有序参考图。编辑要求直接写进正向提示，负面提示不参与此引擎。':input.value==='wan2.2-a14b'?' A14B 需要首帧图片，先验证单镜头效果。':''):'当前服务尚未提供引擎清单，请完成后端更新并刷新。'}
 const engines={image:document.querySelector('[data-group="image"][data-key="engine"]')?.value||config.image?.engine,motion:document.querySelector('[data-group="motion"][data-key="engine"]')?.value||config.motion?.engine};for(const input of document.querySelectorAll('[data-group="models"]')){const key=input.dataset.key,unused=(engines.image==='flux2-klein-4b'&&key.startsWith('image_'))||(engines.motion==='wan2.2-a14b'&&['video_unet','video_vae'].includes(key));input.closest('label').hidden=unused;}}
 function switchVisualEngine(input){const group=input.dataset.group,next=input.value,previous=input.dataset.previousEngine||visualFallback[group];config=read();visualCache[group].set(previous,{...config[group],engine:previous});const profile=visualProfiles(group).find(row=>row.id===next);const restored=visualCache[group].get(next);const defaults={...(profile?.defaults||{})};if(next==='flux2-klein-4b'){defaults.steps=4;defaults.cfg=1}config[group]={...config[group],...(restored||defaults),engine:next};render();const state=document.getElementById('creation-status');if(state)state.textContent=(restored?'已恢复该引擎在本页的参数。':'已采用 '+(visualNames[next]||next)+' 的建议参数。')+'仅作用于本次设置，未保存为全局默认。';document.dispatchEvent(new CustomEvent('creation-engine-changed',{detail:{group,engine:next}}));}
 const qwenChecks=new Map();
 async function checkQwen(group,engine){let hint=group.querySelector('.engine-health');if(!hint){hint=document.createElement('p');hint.className='small engine-health';group.append(hint)}hint.style.display='';hint.textContent='正在检查所选 Qwen3-TTS 本地模型…';try{if(!qwenChecks.has(engine))qwenChecks.set(engine,api('/api/voice-library/qwen-status?engine='+encodeURIComponent(engine)));const result=await qwenChecks.get(engine);if(group.querySelector('[data-key="engine"]')?.value!==engine)return;hint.textContent=(result.ready?'本地文件检查通过，首次试配音仍需验证。':'所选 Qwen3-TTS 模型尚未就绪。')+' '+(result.checks||[]).filter(row=>!row.ready).map(row=>row.message).join(' ')}catch(error){qwenChecks.delete(engine);if(group.querySelector('[data-key="engine"]')?.value===engine)hint.textContent='模型状态检查失败：'+error.message+'。配音时会明确检查，不会自动切换引擎。'}}
 function updateEmotionMode(){for(const select of document.querySelectorAll('[data-group="voice"][data-key="prosody_reference"]')){
  const group=select.closest('.control-group'),engine=group?.querySelector('[data-key="engine"]')?.value||'index-tts',qwen=engine.startsWith('qwen3-');
  for(const key of ['emotion','intensity']){const field=group?.querySelector('[data-key="'+key+'"]');if(field)field.disabled=qwen||!!select.value}
  const strength=group?.querySelector('[data-key="prosody_strength"]');if(strength)strength.disabled=qwen||!select.value;
  for(const field of group.querySelectorAll('[data-group="voice"][data-key]')){const key=field.dataset.key;let hidden=(key.startsWith('qwen_')&&!qwen)||(qwen&&['emotion','intensity','prosody_reference','prosody_strength','duration_factor'].includes(key));if(key==='qwen_speaker')hidden=engine!=='qwen3-custom';if(key==='qwen_instruct')hidden=!['qwen3-custom','qwen3-design'].includes(engine);if(key==='qwen_ref_text')hidden=engine!=='qwen3-clone';if(key==='reference')hidden=['qwen3-custom','qwen3-design'].includes(engine);field.closest('label').style.display=hidden?'none':''}
  const prosodyNote=group.querySelector('.prosody-note');if(prosodyNote)prosodyNote.style.display=qwen?'none':'';
  let hint=group.querySelector('.engine-note');if(!hint){hint=document.createElement('p');hint.className='small engine-note';group.append(hint)}hint.textContent=engineNotes[engine]||'';
  const tools=group.querySelector('.reference-tools');if(tools)tools.style.display=['qwen3-custom','qwen3-design'].includes(engine)?'none':'';
  if(qwen)checkQwen(group,engine);else{const health=group.querySelector('.engine-health');if(health)health.style.display='none'}
 }updateProcessingState(true)}
 function updateProcessingState(reveal=false){for(const engine of document.querySelectorAll('[data-group="voice"][data-key="engine"]')){const group=engine.closest('.control-group'),value=key=>Number(group.querySelector('[data-key="'+key+'"]')?.value),speed=value('speed'),pitch=value('pitch_semitones'),formant=value('formant_shift'),active=speed!==1||pitch!==0||formant!==1;let panel=group.querySelector('.processing-state');if(!panel){panel=document.createElement('div');panel.className='processing-state';const text=document.createElement('p'),reset=document.createElement('button');text.className='small';reset.type='button';reset.className='secondary';reset.textContent='将语速、音高、共鸣设为原值';reset.onclick=()=>{for(const [key,number]of [['speed',1],['pitch_semitones',0],['formant_shift',1]]){const input=group.querySelector('[data-key="'+key+'"]');input.value=number;input.dispatchEvent(new Event('input',{bubbles:true}))}updateProcessingState()};panel.append(text,reset);group.querySelector('.control-grid').after(panel)}panel.querySelector('p').textContent=`${active?'后期调音已启用':'不作语速、音高或共鸣变声'}：语速 ${speed} × · 音高 ${pitch} 半音 · 共鸣 ${formant}。`;panel.querySelector('button').hidden=!active;if(active&&reveal){const details=group.querySelector('details');if(details)details.open=true}}}
 document.addEventListener('input',event=>{if(event.target?.dataset?.group==='voice'&&['speed','pitch_semitones','formant_shift'].includes(event.target.dataset.key))updateProcessingState()});
 document.addEventListener('change',event=>{const input=event.target;if(input?.dataset?.key==='engine'&&visualFallback[input.dataset.group])switchVisualEngine(input);else if(input?.dataset?.group==='voice'&&['prosody_reference','engine'].includes(input.dataset.key))updateEmotionMode()});
 function read(){const c=JSON.parse(JSON.stringify(config));for(const input of document.querySelectorAll('[data-group][data-key]'))c[input.dataset.group][input.dataset.key]=input.type==='number'?Number(input.value):input.value;if(c.voice.engine==='qwen3-design'||(c.voice.engine==='qwen3-custom'&&config.voice.engine!=='qwen3-custom'))c.voice.reference='';return c}
 function set(c){config=c;visualCache.image.clear();visualCache.motion.clear();render();document.dispatchEvent(new CustomEvent('creation-settings-changed'))}
 function error(e){const t=document.getElementById('creation-status');if(t)t.textContent=e.message;else console.error(e)}
 const ready=api('/api/creation').then(d=>{inventory=d;config=d.settings;render();return d}).catch(e=>{error(e);throw e});
 return {api,ready,read,set,select,get inventory(){return inventory},async save(){await ready;const r=await api('/api/creation',read());config=r.settings;return r}};
})();
