(()=>{
 'use strict';
 const $=id=>document.getElementById(id), draftKey='studio-generation-drafts-v1', jobKey='studio-generation-current-job-v1';
 const isFriend=document.documentElement.dataset.studioEdition==='friend'||document.querySelector('meta[name="studio-edition"]')?.content==='friend';
 const friendRouteIds=new Set(['code-animation','whiteboard']);
 const fallbackRoutes=[
  {id:'code-animation',title:'代码动画',description:'信息图、艺术动效与有节奏的文字画面。'},
  {id:'character-story',title:'角色叙事',description:'火柴人、绘本或写实故事，逐镜头生成。'},
  {id:'character-loop',title:'角色循环动画',description:'真实关键姿势组成透明动画素材。'},
  {id:'blender-previs',title:'3D 镜头预演',description:'先用白模验证相机路线与空间关系。'},
  {id:'whiteboard',title:'手绘白板',description:'跟着旁白展开图形与逐笔书写。'},
  {id:'knowledge-film',title:'知识长片',description:'用章节、来源和素材讲清一个主题。'}
 ];
 const icons={
  'code-animation':'<path d="m8 7-5 5 5 5m8-10 5 5-5 5m-3-12-2 18"/>',
  'character-story':'<circle cx="9" cy="6" r="3"/><path d="M3 20v-3a6 6 0 0 1 12 0v3m2-12h5v9h-5m0-5h3"/>',
  'character-loop':'<path d="M20 8a8 8 0 0 0-14-3L3 8m0-5v5h5m-4 8a8 8 0 0 0 14 3l3-3m0 5v-5h-5"/><path d="m10 8 5 4-5 4Z"/>',
  'blender-previs':'<path d="m12 2 9 5v10l-9 5-9-5V7Zm0 10 9-5m-9 5L3 7m9 5v10M7 4l10 6"/>',
  whiteboard:'<path d="M3 4h18v13H3Zm9 13v5m-5 0 5-5 5 5M7 9h5m-5 4h9"/>',
  'knowledge-film':'<path d="M3 4h7a2 2 0 0 1 2 2v15a4 4 0 0 0-4-2H3Zm18 0h-7a2 2 0 0 0-2 2v15a4 4 0 0 1 4-2h5ZM6 8h3m-3 4h3m6-4h3m-3 4h3"/>'
 };
 let catalog=null,voices=[],gallery=[],plan=null,route='code-animation',busy=false,dirty=false,currentJob=null,activeJob=null,jobSignature='',polling=false,loadedDraftJob='',invalidFocus=null,editEpoch=0,planReadSequence=0,codeImportSequence=0;
 // The server catalog is authoritative; fallbacks only supply known display text.
 function availableRoutes(){const candidates=Array.isArray(catalog?.routes)?catalog.routes:fallbackRoutes;return candidates.filter(info=>fallbackRoutes.some(fallback=>fallback.id===info.id)&&(!isFriend||friendRouteIds.has(info.id))).map(info=>({...fallbackRoutes.find(fallback=>fallback.id===info.id),...info}))}
 function applyEditionVisibility(){if(!isFriend)return;const disabled=new Set(['/model-library','/models','/runtime-settings','/image','/motion','/music','/subtitles','/enhance','/director','/novel','/production','/investigation']);for(const link of document.querySelectorAll('a[href]')){const url=new URL(link.getAttribute('href'),location.origin);if(url.origin===location.origin&&disabled.has(url.pathname)){link.hidden=true;link.setAttribute('aria-hidden','true');link.tabIndex=-1}}}
 const node=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el};
 const button=(text,fn,cls='quiet')=>{const el=node('button',text,cls);el.type='button';el.onclick=fn;return el};
 async function api(url,data){const response=await fetch(url,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});let result;try{result=await response.json()}catch{throw Error('工作台没有返回有效结果，请检查服务连接。')}if(!response.ok)throw Error(result.error||result.message||`请求失败（${response.status}）`);return result}
 function status(text,error=false){$('generation-status').textContent=text;$('generation-status').classList.toggle('error',error)}
 // A clean draft can still be newer than a pending GET after a successful save.
 // Invalidate all older plan reads on every local transition, not only dirty edits.
 function advancePlanEpoch(){editEpoch++;planReadSequence++}
 function planView(){return {id:plan?.id||null,route,epoch:editEpoch}}
 function samePlanView(view){return view.id===(plan?.id||null)&&view.route===route&&view.epoch===editEpoch}
 function beginPlanRead(id){return {...planView(),targetId:id,sequence:++planReadSequence}}
 function canApplyPlanRead(read,incoming,{allowBusy=false,allowRouteChange=false}={}){return read.sequence===planReadSequence&&samePlanView(read)&&(allowBusy||!busy)&&incoming?.id===read.targetId&&(allowRouteChange||incoming.route===read.route)&&Number.isInteger(incoming.revision)&&incoming.revision>=(plan?.revision||0)}
 function blankShot(){return {id:'shot-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6),narration:'',visual:'',action:'',camera:'固定镜头',duration:4,reference:'',voice_id:'',status:'planned',review:'',asset_path:''}}
 function blankPlan(){return {title:'',route,brief:'',style:'',character:'',voice_id:'',shots:[blankShot()]}}
 function collect(){if(!plan)return null;for(const [key,id] of Object.entries({title:'plan-title',brief:'plan-brief',style:'plan-style',character:'plan-character',voice_id:'plan-voice'}))plan[key]=$(id).value;plan.route=route;return plan}
 function execution(){return Object.fromEntries(['code-html','code-width','code-height','code-fps','code-duration','code-audio','loop-frames','loop-width','loop-height','loop-fps','loop-background','blender-subject','blender-camera','blender-duration','blender-fps','blender-width','blender-height','blender-distance','story-motion'].map(id=>[id,$(id).type==='checkbox'?$(id).checked:$(id).value]))}
 const defaultExecution=execution();
 function restoreExecution(values){for(const [id,value]of Object.entries(values||{})){const input=$(id);if(input){if(input.type==='checkbox')input.checked=Boolean(value);else input.value=value}}}
 function drafts(){try{return JSON.parse(localStorage.getItem(draftKey)||'{}')}catch{return {}}}
 function remember(){if(!plan)return;try{const all=drafts();all[route]={plan:collect(),execution:execution(),dirty};localStorage.setItem(draftKey,JSON.stringify(all))}catch{status('当前修改仍在页面中，但浏览器备份空间不足，请保存创作计划。',true)}}
 function changed(){advancePlanEpoch();dirty=true;$('save-state').textContent='有未保存修改';$('save-state').classList.add('is-dirty');updateShotCount();remember()}
 function moveTo(element,{focus=true}={}){if(!element)return;for(let parent=element.parentElement;parent;parent=parent.parentElement)if(parent.tagName==='DETAILS')parent.open=true;element.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});if(focus)element.focus({preventScroll:true})}
 function invalid(input,message){invalidFocus=input;if(input){input.setAttribute('aria-invalid','true');input.addEventListener('input',()=>input.removeAttribute('aria-invalid'),{once:true});if(!busy)moveTo(input)}throw Error(message)}
 function shotField(id,key){return [...$('shot-list').children].find(card=>card.dataset.shotId===id)?.querySelector(`[data-field="${key}"]`)}
 function updateShotCount(){if(!plan)return;const duration=plan.shots.reduce((sum,shot)=>sum+(Number.isFinite(shot.duration)?shot.duration:0),0),fixes=plan.shots.filter(shot=>shot.status==='needs-fix').length;$('shot-count').textContent=`${plan.shots.length} 个镜头 · 计划约 ${Math.round(duration*10)/10} 秒${fixes?' · '+fixes+' 镜需要返修':''} · 最终时长以实际音轨为准`;if(!busy)$('add-shot').disabled=plan.shots.length>=128}
 function validatePlan(){if(!plan)throw Error('请先选择生成方式。');collect();if(!plan.title.trim())invalid($('plan-title'),'请先填写作品名称。');if(plan.title.trim().length>140)invalid($('plan-title'),'作品名称最多 140 字，请缩短后保存。');for(const [key,id,limit]of [['brief','plan-brief',12000],['style','plan-style',6000],['character','plan-character',6000]])if(plan[key].trim().length>limit)invalid($(id),`此项最多 ${limit.toLocaleString()} 字，请精简后保存。`);for(const shot of plan.shots){if(!Number.isFinite(shot.duration)||shot.duration<.1||shot.duration>600)invalid(shotField(shot.id,'duration'),'镜头计划时长应在 0.1–600 秒之间。');if(['generated','approved'].includes(shot.status)&&!shot.asset_path.trim())invalid(shotField(shot.id,'asset_path'),'已生成的镜头需要关联实际素材路径。');if(shot.status==='approved'&&shot.review.trim().length<4)invalid(shotField(shot.id,'review'),'验收镜头前，请填写至少 4 字的实际审片意见。')}return plan}
 function assertCanGenerate(){if(activeJob)throw Error('已有生成任务正在运行。可以继续编辑草稿，任务完成后再提交新版本。')}
 function paintActivity(){const banner=$('generation-job-banner');banner.hidden=!activeJob;if(activeJob){const same=currentJob?.id===activeJob.id,version=activeJob.plan_revision||currentJob?.revision;$('generation-job-message').textContent=`${activeJob.status==='queued'?'任务排队中':'任务生成中'}${version?' · 使用已提交的版本 '+version:''}。可以继续编辑，当前修改不会改变已提交任务。`;const link=banner.querySelector('a');link.href=same?'#current-result':'/library';link.textContent=same?'查看任务与结果 ↓':'在作品库查看运行任务 →'}updateEngine()}
 function voiceSelect(value,inherit=false){const select=document.createElement('select');select.append(new Option(inherit?'跟随全片声线':'沿用我的默认声线', ''));for(const voice of voices)select.append(new Option(voice.name,voice.id));if(value&&!voices.some(v=>v.id===value))select.append(new Option('原声线（请到音色库确认）',value));select.value=value||'';return select}
 function paintVoice(){const value=plan?plan.voice_id:$('plan-voice').value,select=voiceSelect(value);$('plan-voice').replaceChildren(...select.children);$('plan-voice').value=value||''}
 function field(parent,title,value,onChange,{type='text',rows=2,placeholder='',wide=false,maximum=4000,key=''}={}){const label=node('label',title,wide?'wide':undefined),input=document.createElement(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;if(type==='textarea')input.rows=rows;input.value=value??'';input.placeholder=placeholder;if(key)input.dataset.field=key;if(type==='number'){input.min='0.1';input.max='600';input.step='0.1'}else input.maxLength=maximum;input.oninput=()=>{onChange(type==='number'?Number(input.value):input.value);changed()};label.append(input);parent.append(label);return input}
 function renderShots(){const list=$('shot-list'),focused=document.activeElement,focusedShot=focused?.closest('.shot-card')?.dataset.shotId,focusedKey=focused?.dataset.field,selection=focusedKey&&['text','textarea'].includes(focused.type)?[focused.selectionStart,focused.selectionEnd]:null,expanded=new Map([...list.children].map(card=>[card.dataset.shotId,card.open]));list.replaceChildren();for(const [i,shot] of plan.shots.entries()){
  const card=node('details',undefined,'shot-card');card.dataset.shotId=shot.id;card.open=expanded.has(shot.id)?expanded.get(shot.id):i===0||shot.status==='needs-fix';const summary=node('summary'),title=node('strong',shot.visual||shot.narration||'还没有画面描述'),badge=node('span','', 'shot-badge');
  const statusNames={planned:'待生成',generated:'已生成 · 待审片','needs-fix':'需要返修',approved:'已人工验收'};
  const paintBadge=()=>{badge.textContent=`${shot.duration} 秒 · ${statusNames[shot.status]||shot.status}`;badge.className='shot-badge '+shot.status};paintBadge();summary.append(node('span',String(i+1).padStart(2,'0'),'shot-number'),title,badge);card.append(summary);
  const body=node('div',undefined,'shot-body'),grid=node('div',undefined,'generation-fields shot-fields');
  field(grid,'画面要表达什么',shot.visual,v=>{shot.visual=v;title.textContent=v||shot.narration||'还没有画面描述'},{type:'textarea',rows:3,maximum:6000,key:'visual',placeholder:'观众先看什么，这一镜揭示什么信息？'});
  field(grid,'旁白或台词',shot.narration,v=>{shot.narration=v;if(!shot.visual)title.textContent=v||'还没有画面描述'},{type:'textarea',rows:3,maximum:6000,key:'narration',placeholder:'一句只讲一个意思，可以先留空。'});
  field(grid,'主体动作',shot.action,v=>shot.action=v,{key:'action',placeholder:'一个主要动作，写明动作与反应。'});
  field(grid,'相机与运镜',shot.camera,v=>shot.camera=v,{maximum:2000,key:'camera',placeholder:'方向、速度、起点、终点；不需要动时就固定。'});
  field(grid,'预计时长（秒）',shot.duration,v=>{shot.duration=v;paintBadge()},{type:'number',key:'duration'});
  const voiceLabel=node('label','这句使用的声线'),voice=voiceSelect(shot.voice_id,true);voice.onchange=()=>{shot.voice_id=voice.value;changed()};voiceLabel.append(voice);grid.append(voiceLabel);
  const referenceLabel=node('label','从图库选择角色或画面参考','wide'),reference=document.createElement('select');reference.append(new Option('暂不指定参考图',''));for(const asset of gallery)reference.append(new Option(asset.title||asset.name||'图库图片',asset.absolute_path));if(shot.reference&&!gallery.some(a=>a.absolute_path===shot.reference))reference.append(new Option('已有参考（展开高级可查看）',shot.reference));reference.value=shot.reference||'';referenceLabel.append(reference);grid.append(referenceLabel);const referenceDetails=node('details',undefined,'wide');referenceDetails.append(node('summary','高级：参考文件或链接'));const referencePath=field(referenceDetails,'参考路径',shot.reference,v=>{shot.reference=v;if(v&&![...reference.options].some(option=>option.value===v))reference.append(new Option('自定义参考',v));reference.value=v},{placeholder:'本机完整路径或参考链接'});reference.onchange=()=>{shot.reference=reference.value;referencePath.value=reference.value;changed()};grid.append(referenceDetails);body.append(grid);
  const review=node('div',undefined,'generation-fields shot-review');review.append(node('p','审片与返修','wide shot-review-title'));const mediaDetails=node('details',undefined,'wide shot-media');mediaDetails.append(node('summary',shot.asset_path?'已关联素材 · 查看或调整路径':'关联已有素材（生成后会自动填写）'));field(mediaDetails,'实际素材路径',shot.asset_path,v=>shot.asset_path=v,{maximum:2000,key:'asset_path',placeholder:'自动关联生成结果，也可填写已有本机媒体路径。'});review.append(mediaDetails);
  const stateLabel=node('label','审片状态'),state=document.createElement('select');for(const [value,name] of Object.entries(statusNames))state.append(new Option(name,value));state.value=shot.status||'planned';state.onchange=()=>{shot.status=state.value;paintBadge();changed()};stateLabel.append(state);review.append(stateLabel);
  field(review,'审片意见与返修要求',shot.review,v=>shot.review=v,{type:'textarea',wide:true,maximum:16000,key:'review',placeholder:'例如：角色衣服一致，镜头平稳，结尾动作已闭合。或：第 2 秒手部变形，需要重做。'});body.append(review,node('p','选择“已人工验收”时，需要真实素材和至少 4 字审片意见。生成成功不会自动通过验收。','small'));
  const tools=node('div',undefined,'shot-toolbar');if(!isFriend){const motion=button('带入短镜头生成',async()=>{try{validatePlan();setBusy(true);await savePlan();sessionStorage.setItem('director-motion',[plan.character,plan.style,shot.visual,shot.action,shot.camera].filter(Boolean).join('\n'));const image=/^[A-Za-z]:[\\/]/.test(shot.reference||'')?`?image=${encodeURIComponent(shot.reference)}`:'';location.assign('/motion'+image)}catch(error){status(error.message,true)}finally{setBusy(false)}},'quiet');tools.append(motion)}
  const up=button('↑ 前移',()=>{[plan.shots[i-1],plan.shots[i]]=[plan.shots[i],plan.shots[i-1]];changed();renderShots();moveTo([...$('shot-list').children].find(item=>item.dataset.shotId===shot.id)?.querySelector('summary'))});up.disabled=i===0;up.setAttribute('aria-label',`将第 ${i+1} 镜前移`);tools.append(up);
  const remove=button('移除此镜头',()=>{plan.shots.splice(i,1);if(!plan.shots.length)plan.shots.push(blankShot());changed();renderShots();moveTo($('shot-list').children[Math.min(i,plan.shots.length-1)]?.querySelector('summary'));status('已移除镜头；修改尚未保存。')},'quiet remove-shot');remove.setAttribute('aria-label',`移除第 ${i+1} 镜`);tools.append(remove);body.append(tools);card.append(body);list.append(card);
 }updateShotCount();if(focusedShot&&focusedKey){const restored=shotField(focusedShot,focusedKey);if(restored){restored.focus({preventScroll:true});if(selection)restored.setSelectionRange(...selection)}}}
 function paintPlan(){for(const [key,id]of Object.entries({title:'plan-title',brief:'plan-brief',style:'plan-style',character:'plan-character'}))$(id).value=plan[key]||'';paintVoice();renderShots();$('plan-version').textContent=plan.id?`版本 ${plan.revision}`:'新创作';$('plan-version').title=plan.id||'';$('save-state').textContent=dirty?'有未保存修改':plan.id?'已保存到作品库':'尚未保存';$('save-state').classList.toggle('is-dirty',dirty);$('reload-plan').hidden=!plan.id}
 function runtimeForRoute(){return catalog?.runtime?.[{'code-animation':'code_animation','character-loop':'character_loop','blender-previs':'blender'}[route]]}
 function updateEngine(){const generated=['code-animation','character-story','character-loop','blender-previs'].includes(route),runtime=runtimeForRoute(),ready=route==='character-story'||Boolean(runtime?.ready);$('engine-status').textContent=route==='character-story'?'使用当前图像与视频模型配置':ready?(route==='character-loop'?'组帧环境就绪':'渲染环境就绪'):'渲染环境未就绪';$('engine-status').classList.toggle('ready',ready&&route!=='character-story');$('render-actions').hidden=!generated;$('render-blocker').hidden=!generated||ready;$('render-blocker').textContent=runtime?.message||runtime?.reason||(route==='blender-previs'?'尚未检测到可用 Blender。准备好 Blender 后刷新环境，再生成白模预演。':'生成环境还未通过检查。请查看本地环境或稍后刷新页面。');for(const id of ['render-preview','render-final','manual-preview','manual-render','manual-loop','manual-blender'])$(id).disabled=busy||Boolean(activeJob)||!ready;$('draft-plan').disabled=busy||Boolean(activeJob);$('retry-job').disabled=busy||Boolean(activeJob);$('render-preview').textContent=route==='code-animation'?'生成动画样片':'生成样片';$('render-final').textContent=route==='character-loop'?'生成循环动画':route==='blender-previs'?'生成完整预演':route==='character-story'?'生成完整片段':'生成完整动画';for(const [id,value]of [['code-controls','code-animation'],['loop-controls','character-loop'],['blender-controls','blender-previs'],['story-controls','character-story']])$(id).hidden=route!==value}
 function showRoute(next,{restore=true}={}){const routes=availableRoutes();if(!routes.length)throw Error('当前版本暂无可用创作方式，请检查工作台配置。');advancePlanEpoch();if(!routes.some(r=>r.id===next))next=routes.find(r=>r.id==='code-animation')?.id||routes[0].id;if(plan)remember();route=next;for(const card of $('generation-routes').children)card.setAttribute('aria-pressed',String(card.dataset.route===route));const info=routes.find(r=>r.id===route);$('route-status').textContent=info.description||'';const existing=route==='whiteboard'||route==='knowledge-film';$('existing-editor').hidden=!existing;$('generation-editor').hidden=existing;
  if(existing){$('existing-title').textContent=info.title;$('existing-description').textContent=route==='whiteboard'?'继续使用白板编辑器，修改旁白、布局和人物贴纸，再生成静帧与有声视频。':'继续使用长片编辑器，组织来源、章节、画面覆盖和配音，再预览与渲染。';$('existing-link').href=route==='whiteboard'?'/whiteboard':'/investigation';$('existing-link').textContent='打开'+info.title;plan=null;dirty=false}else{const saved=restore?drafts()[route]:null;plan=saved?.plan||blankPlan();dirty=Boolean(saved?.dirty);restoreExecution(defaultExecution);restoreExecution(saved?.execution);paintPlan();updateEngine();updateCodeSummary()}
  $('handoff-view').hidden=true;$('current-result').hidden=true;currentJob=null;jobSignature='';for(const step of document.querySelectorAll('[data-generation-step]')){step.setAttribute('aria-disabled',String(existing&&step.dataset.generationStep!=='route'));step.toggleAttribute('aria-current',step.dataset.generationStep==='route');if(step.hasAttribute('aria-current'))step.setAttribute('aria-current','step')}updateUrl();status(existing?'该创作方式使用已有编辑器；所有成片仍在“我的作品”中管理。':plan.id?'已恢复本机创作计划，可继续修改。':'写下内容和风格，点击“生成创作方案”开始。');restoreJob();paintActivity();
 }
 function updateUrl(){const query=new URLSearchParams();query.set('route',route);if(plan?.id)query.set('id',plan.id);history.replaceState(null,'','/generation?'+query)}
 function renderRoutes(){const box=$('generation-routes');box.replaceChildren();for(const info of availableRoutes()){const card=button('',()=>{if(!busy)showRoute(info.id)},'route-card');card.dataset.route=info.id;card.setAttribute('aria-pressed','false');const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('route-icon');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');svg.innerHTML=icons[info.id];card.append(svg,node('strong',info.title),node('span',info.description));box.append(card)}}
 function setBusy(value){busy=value;$('generation-editor').inert=value;$('generation-editor').setAttribute('aria-busy',String(value));for(const id of ['save-plan','copy-handoff','new-plan','reload-plan','add-shot','load-code-example','draft-plan'])$(id).disabled=value;for(const card of $('generation-routes').children)card.disabled=value;updateEngine();if(!value){updateShotCount();if(invalidFocus){const input=invalidFocus;invalidFocus=null;moveTo(input)}}}
 async function savePlan(){
  validatePlan();advancePlanEpoch();const view=planView(),submitted=JSON.parse(JSON.stringify(plan));
  const result=await api('/api/generation/plan',submitted),saved=result.plan||result;
  if(!samePlanView(view)||saved.route!==view.route||(view.id&&saved.id!==view.id)||!Number.isInteger(saved.revision)||saved.revision<(plan?.revision||0))throw Error('提交版本已保存，但页面已有其他修改或已切换。当前内容保留，请确认后再继续。');
  advancePlanEpoch();plan=saved;dirty=false;paintPlan();remember();updateUrl();status('创作计划已保存；可以从“我的作品”继续打开。');return plan
 }
 async function saveClick(){try{validatePlan();setBusy(true);await savePlan()}catch(error){status(error.message,true)}finally{setBusy(false)}}
 function updateCodeSummary(){$('code-summary').textContent=$('code-html').value.trim()?`已准备画面代码（${$('code-html').value.length.toLocaleString()} 字符）。点击本区“预览导入的动画”进行检查。`:'还没有画面代码。'}
 function number(id){const el=$(id);if(!el.reportValidity())throw Error('请检查生成参数。');const value=Number(el.value);if(!Number.isFinite(value)||value<=0)throw Error('生成参数必须为有效的正数。');return value}
 function renderPayload(){if(route==='code-animation'){if(!$('code-html').value.trim())throw Error('请先载入示例或导入 Codex 写好的画面代码。');const audio=$('code-audio').value.trim();return {html:$('code-html').value,width:number('code-width'),height:number('code-height'),fps:number('code-fps'),duration:number('code-duration'),...(audio?{audio_path:audio}:{})}}
  if(route==='character-loop'){const frames=$('loop-frames').value.split(/\r?\n/).map(s=>s.trim().replace(/^"|"$/g,'')).filter(Boolean);if(frames.length<4)throw Error('至少需要 4 张真实关键姿势图，每行填写一个完整路径。');return {frames,width:number('loop-width'),height:number('loop-height'),fps:number('loop-fps'),background:$('loop-background').value}}
  return {duration:number('blender-duration'),fps:number('blender-fps'),width:number('blender-width'),height:number('blender-height'),camera:$('blender-camera').value,subject:$('blender-subject').value,distance:number('blender-distance')};
 }
 async function startJob(result,{preview=false,operation='render'}={}){currentJob={id:result.job_id,plan_id:plan.id,route,preview,operation,revision:plan.revision};activeJob={...currentJob,plan_revision:plan.revision,status:'queued'};jobSignature='';try{sessionStorage.setItem(jobKey,JSON.stringify(currentJob))}catch{status('任务已提交，浏览器会话备份暂不可用；可在作品库查看任务。',true)}paintActivity();$('current-result').hidden=false;$('retry-section').hidden=true;$('job-media').replaceChildren();$('render-status').textContent=`${operation==='draft'?'创作方案':preview?'样片':'片段'}已提交 · 版本 ${plan.revision}`;await poll();moveTo($('current-result'),{focus:false})}
 async function render(preview,manual=false){$('render-status').classList.remove('error');try{assertCanGenerate();const automatic=!manual,payload=automatic?null:renderPayload();validatePlan();setBusy(true);await savePlan();const result=automatic?await api('/api/generation/compose',{plan_id:plan.id,revision:plan.revision,preview,backend:'auto',motion_enabled:route==='character-story'&&$('story-motion').checked}):await api('/api/generation/render',{plan_id:plan.id,kind:route,preview,payload});await startJob(result,{preview,operation:automatic?'compose':'render'})}catch(error){$('render-status').textContent=error.message;$('render-status').classList.add('error');status(error.message,true)}finally{setBusy(false)}}
 async function draft(){try{assertCanGenerate();if(!$('plan-brief').value.trim())invalid($('plan-brief'),'先写下想做的内容和目标，工作台才能为你设计分镜。');if(!$('plan-title').value.trim())$('plan-title').value=$('plan-brief').value.trim().split(/\r?\n/)[0].slice(0,60);validatePlan();setBusy(true);await savePlan();const result=await api('/api/generation/draft',{plan_id:plan.id,revision:plan.revision,backend:'auto'});await startJob(result,{operation:'draft'})}catch(error){status(error.message,true)}finally{setBusy(false)}}
 function safeMedia(value){if(typeof value!=='string')return '';try{const url=new URL(value,location.origin);return url.origin===location.origin&&url.pathname.startsWith('/outputs/')?url.href:''}catch{return ''}}
 async function poll(){if(polling)return;polling=true;const observedJob=currentJob,target=observedJob?.id;try{const jobs=await api('/api/jobs');
   // startJob/retry replace the tracker, even when retry keeps the same job ID.
   // A response requested before that transition must not clear its queued state.
   if(currentJob!==observedJob)return;
   const running=Object.entries(jobs).find(([,job])=>job.kind==='generation'&&['queued','running'].includes(job.status));activeJob=running?{...running[1],id:running[0]}:null;paintActivity();if(!target||currentJob?.id!==target)return;const job=jobs[target];if(!job){$('job-state').textContent='本次任务暂未出现在列表中，正在等待状态更新。';return}const names={queued:'排队中',running:'生成中',done:'生成完成',error:'生成失败',cancelled:'已取消'},isPreview=job.preview??currentJob.preview,isDraft=currentJob.operation==='draft';$('current-result').hidden=false;$('retry-section').hidden=job.status!=='error'||currentJob.operation!=='compose';$('job-state').textContent=`${isDraft?'创作方案':isPreview?'样片预览':'生成片段'} · ${names[job.status]||job.status}${job.phase?' · '+job.phase:''}${job.error?' · '+job.error:''}`;$('job-state').classList.toggle('error',job.status==='error');
    if(!busy&&['draft','compose','render'].includes(currentJob.operation)&&job.status==='done'&&loadedDraftJob!==target){
     const read=beginPlanRead(job.plan_id||currentJob.plan_id),result=await api('/api/generation/plan?id='+encodeURIComponent(read.targetId)),incoming=result.plan||result;
     if(currentJob?.id!==target)return;
     loadedDraftJob=target;
     if(dirty||!canApplyPlanRead(read,incoming)){status('生成结果已保存到作品库。页面已有编辑、保存或载入操作，当前内容保持不变；可从作品库查看成果。')}
     else{advancePlanEpoch();plan=incoming;paintPlan();remember();updateUrl();status(isDraft?'创作方案已生成。查看分镜，需要时直接修改，再生成样片。':job.plan_attached===false?(job.plan_update_note||'产物已保存，未自动关联到当前分镜，请检查本次结果。'):'生成结果已同步到创作计划，请播放检查后填写审片意见。');if(isDraft)moveTo($('shots-heading'),{focus:false})}
    }
   const signature=JSON.stringify([job.video,job.image,job.gif,job.qa]);if(signature!==jobSignature){jobSignature=signature;const box=$('job-media');box.replaceChildren();const video=safeMedia(job.video),gif=safeMedia(job.gif),image=safeMedia(job.image);if(video){const v=document.createElement('video');v.controls=true;v.preload='metadata';v.src=video;if(image)v.poster=image;box.append(v)}if(gif){const img=node('img');img.src=gif;img.alt='本次角色循环动画';img.className='loop-preview';box.append(img)}else if(image&&!video){const img=node('img');img.src=image;img.alt='本次生成预览';box.append(img)}for(const [label,url]of [['下载视频',video],['下载循环 GIF',gif],['查看检查报告',safeMedia(job.qa)]])if(url){const link=node('a',label);link.href=url;if(label.startsWith('下载'))link.download='';else{link.target='_blank';link.rel='noopener'}box.append(link)}}
   $('job-review').textContent=isDraft?'生成的方案仍可逐镜头修改，保存后再生成样片。':job.status==='done'?(isPreview?'这是样片，用于检查构图、运动与节奏。':'片段已生成。')+' 请实际播放检查；画面、角色和听感不会因任务完成而自动通过。满意后在对应镜头填写素材路径与审片意见。':'当前仅显示这次生成。之前的作品可在“我的作品”中查找。';
  }catch(error){if(currentJob===observedJob)$('job-state').textContent='状态读取失败：'+error.message}finally{polling=false}}
 function restoreJob(){try{const saved=JSON.parse(sessionStorage.getItem(jobKey)||'null');if(saved&&plan?.id===saved.plan_id&&route===saved.route){currentJob=saved;poll()}}catch{}}
 function renderSources(){const list=$('generation-sources');list.replaceChildren();for(const source of catalog.sources||[]){const title=source.title||source.name||source.id,url=source.url||source.source;if(!title)continue;const li=node('li'),link=node('a',title);try{const u=new URL(url);if(!['https:','http:'].includes(u.protocol))continue;link.href=u.href;link.target='_blank';link.rel='noopener noreferrer';li.append(link);if(source.summary||source.description)li.append(document.createTextNode(' · '+(source.summary||source.description)));list.append(li)}catch{}}}
 async function loadGallery(){const result=await api('/api/library?view=assets&kind=image&status=done');gallery=(result.items||[]).filter(a=>a.absolute_path);const host=$('loop-gallery');host.replaceChildren();for(const asset of gallery.slice(0,40)){const card=button('',()=>{$('loop-frames').value=[$('loop-frames').value.trim(),asset.absolute_path].filter(Boolean).join('\n');changed()},'pose-choice');const imageUrl=safeMedia(asset.preview_url||asset.url);if(imageUrl){const img=node('img');img.src=imageUrl;img.alt='';img.loading='lazy';card.append(img)}card.append(node('span',asset.title||'图库图片'));card.title='添加到姿势序列末尾';host.append(card)}if(!gallery.length)host.append(node('p','图库还没有图片。可先生成参考图，也可以展开后直接导入已有图片。','small'));if(plan){collect();renderShots()}}
 $('save-plan').onclick=saveClick;$('add-shot').onclick=()=>{if(plan.shots.length>=128)return;const shot=blankShot();plan.shots.push(shot);changed();renderShots();moveTo(shotField(shot.id,'visual'))};
 $('retry-job').onclick=async()=>{if(!currentJob)return;try{assertCanGenerate();setBusy(true);const preview=currentJob.preview,result=await api('/api/generation/retry',{job_id:currentJob.id});await startJob(result,{preview,operation:'compose'})}catch(error){$('job-state').textContent=error.message;$('job-state').classList.add('error')}finally{setBusy(false)}};
 $('new-plan').onclick=async()=>{try{if(dirty||plan?.title)validatePlan();setBusy(true);if(dirty||plan?.title)await savePlan();advancePlanEpoch();plan=blankPlan();dirty=false;restoreExecution(defaultExecution);paintPlan();updateCodeSummary();remember();$('handoff-view').hidden=true;$('current-result').hidden=true;currentJob=null;updateUrl();paintActivity();status('已新建空白计划；上一份已保存，可以在作品库继续打开。')}catch(error){status('新建前保存未成功，当前内容已保留：'+error.message,true)}finally{setBusy(false)}};
 $('reload-plan').onclick=async()=>{if(!plan?.id)return;setBusy(true);advancePlanEpoch();const read=beginPlanRead(plan.id);try{if(dirty)sessionStorage.setItem('studio-generation-unsaved-backup',JSON.stringify(collect()));const result=await api('/api/generation/plan?id='+encodeURIComponent(read.targetId)),incoming=result.plan||result;if(!canApplyPlanRead(read,incoming,{allowBusy:true})){status('载入期间页面已有其他变化，当前内容未替换。');return}advancePlanEpoch();plan=incoming;dirty=false;paintPlan();remember();updateUrl();status('已重新载入保存的版本。替换前的未保存内容已保留会话备份。')}catch(error){if(samePlanView(read))status(error.message,true)}finally{setBusy(false)}};
 $('copy-handoff').onclick=async()=>{try{validatePlan();setBusy(true);await savePlan();const result=await api('/api/generation/handoff?id='+encodeURIComponent(plan.id));$('handoff-text').value=result.text||'';$('handoff-view').hidden=false;$('handoff-view').open=true;try{await navigator.clipboard.writeText(result.text);status('已复制创作指令，回到 Codex 对话粘贴即可继续。')}catch{setBusy(false);moveTo($('handoff-text'));$('handoff-text').select();status('创作指令已展开，请复制选中的文字。')}}catch(error){status(error.message,true)}finally{setBusy(false)}};
 $('load-code-example').onclick=async()=>{setBusy(true);try{const result=await api('/api/generation/example?kind=code-animation');if(!result.html)throw Error('示例代码为空。');if($('code-html').value.trim())sessionStorage.setItem('studio-generation-code-backup',$('code-html').value);$('code-html').value=result.html;updateCodeSummary();if(!$('plan-title').value.trim())$('plan-title').value='代码动效 · 渲染体验';changed();status('已载入示例，请在高级区点击“预览导入的动画”。已有画面代码会保留一份浏览器会话备份。')}catch(error){status(error.message,true)}finally{setBusy(false)}};
 $('code-file').onchange=async()=>{const file=$('code-file').files[0];if(!file)return;const view=planView(),importSequence=++codeImportSequence;try{if(file.size>2*1024*1024)throw Error('HTML 文件超过 2 MB，请精简或让 Codex 整理项目。');const html=await file.text();if(importSequence!==codeImportSequence||!samePlanView(view)||busy){if(importSequence===codeImportSequence)status('读取文件期间页面已有变化，当前内容未替换；需要时请重新选择文件。');return}if($('code-html').value.trim())sessionStorage.setItem('studio-generation-code-backup',$('code-html').value);$('code-html').value=html;updateCodeSummary();changed();status('已导入 '+file.name+'，请核对尺寸和时长后生成样片。')}catch(error){if(importSequence===codeImportSequence&&samePlanView(view))status(error.message,true)}};
 $('draft-plan').onclick=draft;$('render-preview').onclick=()=>render(true);$('render-final').onclick=()=>render(false);$('manual-preview').onclick=()=>render(true,true);$('manual-render').onclick=()=>render(false,true);$('manual-loop').onclick=()=>render(false,true);$('manual-blender').onclick=()=>render(false,true);$('refresh-gallery').onclick=()=>loadGallery().catch(error=>status('图库读取失败：'+error.message,true));
 for(const id of ['plan-title','plan-brief','plan-style','plan-character','plan-voice',...Object.keys(execution())])$(id).addEventListener('input',()=>{if(id==='code-html')updateCodeSummary();changed()});
 window.addEventListener('beforeunload',()=>remember());
 async function init(){
  const query=new URLSearchParams(location.search),requestedId=query.get('id')||query.get('plan'),initialView=planView();
  try{catalog=await api('/api/generation/catalog');if(!availableRoutes().length)throw Error('当前版本暂无可用创作方式。');renderRoutes();renderSources()}
  catch(error){if(samePlanView(initialView)){status('生成工坊加载失败：'+error.message,true);$('generation-routes').replaceChildren(node('p','请确认工作台已加载新版生成接口，然后刷新页面。'))}return}
  if(samePlanView(initialView)){
   if(requestedId){
    const read=beginPlanRead(requestedId);
    try{
     const result=await api('/api/generation/plan?id='+encodeURIComponent(requestedId)),loaded=result.plan||result;
     if(!availableRoutes().some(info=>info.id===loaded.route))throw Error('当前版本不支持此计划的创作方式');
     if(canApplyPlanRead(read,loaded,{allowRouteChange:true})){
      const saved=drafts()[loaded.route],matching=saved?.plan?.id===loaded.id,pending=matching&&(saved.dirty||saved.plan.revision>loaded.revision)?saved:null;
      showRoute(loaded.route,{restore:false});advancePlanEpoch();plan=pending?.plan||loaded;dirty=Boolean(pending?.dirty);
      if(matching)restoreExecution(saved.execution);paintPlan();updateCodeSummary();remember();updateUrl();restoreJob();
      status(pending?(dirty?'已恢复本机未保存修改。如需放弃这些修改，可点击“重新载入已保存版本”。':'已保留本机较新的计划版本；未用较早的响应替换。'):'已打开保存的创作计划。')
     }
    }catch(error){if(read.sequence===planReadSequence&&samePlanView(read))status('创作计划读取失败：'+error.message+'。可以选择其他创作方式，当前草稿未改动。',true)}
   }else showRoute(query.get('route')||'code-animation')
  }
  const results=await Promise.allSettled([api('/api/voice-library'),loadGallery()]);
  if(results[0].status==='fulfilled'){voices=results[0].value.presets||[];if(plan){collect();paintVoice();renderShots()}}
  else status('创作计划可继续使用；音色库暂时无法读取，已有声线设置会保留。',true);
  if(results[1].status==='rejected')$('loop-gallery').append(node('p','图库暂时无法读取，可点击刷新重试。','small'))
 }
 for(const link of document.querySelectorAll('[data-generation-step]'))link.addEventListener('click',event=>{event.preventDefault();if(link.getAttribute('aria-disabled')==='true'){moveTo($('existing-link'));return}if(busy&&link.dataset.generationStep!=='route')return;for(const other of document.querySelectorAll('[data-generation-step]')){if(other===link)other.setAttribute('aria-current','step');else other.removeAttribute('aria-current')}moveTo($(link.getAttribute('href').slice(1)))});
 if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){for(const link of document.querySelectorAll('[data-generation-step]')){if(link.getAttribute('href')==='#'+entry.target.id)link.setAttribute('aria-current','step');else link.removeAttribute('aria-current')}}},{rootMargin:'-80px 0px -55% 0px',threshold:0});for(const id of ['route-heading','brief-heading','shots-heading','render-heading'])observer.observe($(id))}
 applyEditionVisibility();init();poll();setInterval(poll,4000);
})();
