/* Investigation editor: source text, model output and paths are data only. */
(()=>{
 'use strict';
 const $=id=>document.getElementById(id),storageKey='ai-studio-investigation-v1';
 const modes={account:['账目','从单据和分配关系出发，逐项对照来源。'],cost:['代价','从具体的人与时间点出发，追踪后果。'],rules:['规则','从冲突现场回到条文和执行。'],process:['过程','按时间线推进，每章增加一个转折。'],compare:['对照','先确定参照样本，再找有依据的差异。'],identity:['身份','从实物、主体和证照出发，核对来源。']};
 const kinds={video:'真实视频',image:'图片',evidence:'证据截图',diagram:'机制图解'};
 let spec={version:1,render_mode:'investigation',mode:'investigation',title:'',topic:'',hot_relevance:'',narrative_mode:'rules',target_minutes:10,demo_mode:false,sources:[],chapters:[],scenes:[]};
 let jobId=null,media=[],cast=[],library={presets:[],references:[]},pendingDraft=null,polling=false,actionBusy=false,pendingResource=null,allowPendingDraft=true;
 const jobNodes=new Map();
 const node=(tag,text,className)=>{const item=document.createElement(tag);if(text!==undefined)item.textContent=text;if(className)item.className=className;return item};
 function status(text,error=false){$('action-status').textContent=text;$('action-status').className='status sticky-status'+(error?' error':'')}
 async function api(url,data){const response=await fetch(url,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok){const error=Error(result.error||`请求失败：${response.status}`);error.payload=result;throw error}return result}
 function button(label,callback,className='quiet'){const value=node('button',label,className);value.type='button';value.onclick=callback;return value}
 function field(label,control){const wrapper=node('label',undefined,'form-field');wrapper.append(node('span',label),control);return wrapper}
 function input(value,max,callback,type='input'){const item=node(type);item.value=value??'';if(max)item.maxLength=max;item.oninput=()=>{callback(item.value);store();coverage()};return item}
 function select(options,value,callback){const item=node('select');for(const [id,label]of options)item.append(new Option(label,id));if(value&&!options.some(([id])=>id===value))item.append(new Option(value+' · 未找到',value));item.value=value??'';item.onchange=()=>{callback(item.value);store();coverage()};return item}
 function numeric(value,min,max,callback,step=1){const item=input(value,null,value=>callback(Number(value)));item.type='number';item.min=min;item.max=max;item.step=step;return item}
 function uid(prefix,rows){let n=rows.length+1;while(rows.some(row=>row.id===prefix+String(n).padStart(3,'0')))n++;return prefix+String(n).padStart(3,'0')}
 function knownSourceOptions(){return[['','未关联来源'],...spec.sources.map(source=>[source.id,`${source.id} · ${source.title||'未命名来源'}`])]}
 function presetOptions(label='跟随全片旁白'){return[['',label],...library.presets.map(preset=>[preset.id,preset.name])]}
 function readTop(){spec.topic=$('topic').value;spec.hot_relevance=$('hot-relevance').value;spec.narrative_mode=$('narrative-mode').value;spec.target_minutes=Number($('target-minutes').value);spec.title=$('project-title').value;spec.mode=$('production-mode').value;spec.voice_preset_id=$('voice-preset').value;spec.character_preset_ids=Object.fromEntries(cast.map(role=>[role.name,role.preset]));}
 function store(){readTop();try{localStorage.setItem(storageKey,JSON.stringify({jobId,storyboard:spec,media,pendingDraft}))}catch{}}
 function backupDraft(reason){
  readTop();const snapshot={saved_at:new Date().toISOString(),reason,jobId,storyboard:structuredClone(spec),media:structuredClone(media),pendingDraft};
  let rows=[];try{rows=JSON.parse(localStorage.getItem(storageKey+'-backups')||'[]')}catch{}if(!Array.isArray(rows))rows=[];
  try{localStorage.setItem(storageKey+'-backups',JSON.stringify([...rows.slice(-4),snapshot]))}catch{throw Error('浏览器无法备份当前草稿，已停止替换。请先导出草稿并释放浏览器存储。')}
  let host=$('draft-backup');if(!host){host=node('div',undefined,'small');host.id='draft-backup';$('action-status').after(host)}host.replaceChildren(node('span','载入前的浏览器草稿已备份。 '),button('下载备份',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json'})),link=download(url,'');link.download='investigation-before-load.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},'secondary'));
 }
 function projectContext(){let host=$('project-context');if(!host){host=node('p',undefined,'small');host.id='project-context';$('project-title').parentElement.after(host)}host.textContent=jobId?'当前编辑工程：'+jobId+'。保存会更新此工程的分镜；原视频不会自动重渲染。':'当前为未保存的浏览器草稿。';const main=document.querySelector('main');if(main)main.dataset.currentProject=jobId||''}
 async function loadProject(id){
  if(actionBusy)throw Error('正在保存或登记素材，请完成后再切换工程。');
  if(!/^investigation-[a-f0-9]{10}$/.test(id))throw Error('调查项目编号无效。');
  const data=await api('/api/investigation/project?job_id='+encodeURIComponent(id));
  if(data.job_id!==id||!Array.isArray(data.storyboard?.scenes)||!Array.isArray(data.storyboard?.sources)||!Array.isArray(data.storyboard?.chapters))throw Error('指定项目暂无可恢复的完整分镜。');
  backupDraft('载入项目 '+id);pendingDraft=null;applyProject(data);projectContext();renderPendingResource();status('已载入指定工程 '+id+'。原浏览器草稿已备份，请确认后再保存或制作。');
 }
 function applyProject(data){const value=data.storyboard||data;if(!value||!Array.isArray(value.scenes)||!Array.isArray(value.chapters)||!Array.isArray(value.sources))throw Error('项目缺少来源、章节或镜头数组。');spec=structuredClone(value);spec.mode=spec.mode||'investigation';spec.hot_relevance=spec.hot_relevance||'';spec.narrative_mode=spec.narrative_mode||'rules';spec.target_minutes=spec.target_minutes||10;jobId=data.job_id??null;media=Array.isArray(data.media)?data.media:[];cast=Object.entries(spec.character_preset_ids||spec.characters||{}).map(([name,preset])=>({name,preset:typeof preset==='string'?preset:''}));renderAll();renderPendingResource();showGaps(data.gaps);showDownloads(data.downloads);store()}
 function renderAll(){
  $('topic').value=spec.topic||'';$('hot-relevance').value=spec.hot_relevance||'';$('narrative-mode').value=spec.narrative_mode;$('target-minutes').value=spec.target_minutes;$('project-title').value=spec.title||'';$('production-mode').value=spec.mode;
  const chosen=spec.voice_preset_id||'';$('voice-preset').replaceChildren(...presetOptions('跟随工作台默认音色').map(([id,label])=>new Option(label,id)));if(chosen&&!library.presets.some(item=>item.id===chosen))$('voice-preset').append(new Option(chosen+' · 待加载',chosen));$('voice-preset').value=chosen;
  $('demo-info').hidden=!spec.demo_mode;$('narrative-help').textContent=modes[spec.narrative_mode]?.[1]||'';renderSources();renderAssets();renderCast();renderChapters();coverage();projectContext();
 }
 function renderSources(){
  $('sources').replaceChildren();if(!spec.sources.length)$('sources').append(node('p','添加公开报道、官方文件或原始声明，再编写调查草稿。','empty'));
  spec.sources.forEach(source=>{
   const card=node('details',undefined,'card');card.open=!source.title;const summary=node('summary',`${source.id} · ${source.title||'新来源'}`),grid=node('div',undefined,'grid');
   grid.append(field('来源标题',input(source.title,300,value=>{source.title=value;summary.textContent=`${source.id} · ${value||'新来源'}`})),field('公开日期',input(source.published_at,100,value=>{source.published_at=value})),field('原始链接',input(source.url,2000,value=>{source.url=value})),field('审阅状态',select([['unreviewed','待人工核对'],['source_checked','已查阅原文，仍需核对事实'],['user_reviewed','已由我核对原文']],source.status||'unreviewed',value=>{source.status=value})));
   const content=field('支撑事实的原文或摘录 · AI 按此写稿',input(source.content,16000,value=>{source.content=value},'textarea'));content.classList.add('full');grid.append(content);const tools=node('div',undefined,'toolbar');
   tools.append(button('读取该网页正文',async()=>{try{if(!source.url)throw Error('先填写来源链接。');status('正在读取公开网页正文…');const result=await api('/api/investigation/source',{url:source.url});Object.assign(source,result.source,{id:source.id});renderSources();store();status('已读取网页内容，仍需人工核对事实与日期。')}catch(error){status(error.message,true)}},'secondary'),button('移除来源',()=>{if(spec.scenes.some(scene=>(scene.source_ids||[]).includes(source.id))||media.some(item=>item.source_id===source.id)){status('该来源已关联镜头或素材，请先解除关联。',true);return}spec.sources=spec.sources.filter(item=>item!==source);renderSources();renderAssets();store()}));card.append(summary,grid,tools);$('sources').append(card);
  });$('add-source').disabled=spec.sources.length>=24;
 }
 function coverage(){
  const scenes=spec.scenes||[],associated=scenes.filter(scene=>scene.kind==='diagram'||media.some(item=>item.id===scene.media_id)).length,reviewed=scenes.filter(scene=>['user_reviewed','analysis'].includes(scene.fact_status)).length,chars=scenes.reduce((sum,scene)=>sum+(scene.narration||'').length,0);
  $('coverage').replaceChildren();for(const [value,label]of [[spec.chapters.length+' / '+scenes.length,'章节 / 镜头'],[`${associated} / ${scenes.length}`,'有素材关联或图解'],[`${reviewed} / ${scenes.length}`,'人工审阅 / 解释段'],[chars,'旁白字数 · 非实际时长']]){const metric=node('div',undefined,'metric');metric.append(node('strong',String(value)),node('span',label));$('coverage').append(metric)}
 }
 function renderAssets(){
  $('assets').replaceChildren();if(!media.length)$('assets').append(node('p','尚未导入素材。完成分镜后保存项目，再登记已有本地文件。','small'));
  for(const item of media){const card=node('details',undefined,'card');card.append(node('summary',`${item.id} · ${item.kind==='audio'?'音频素材':kinds[item.kind]||item.kind} · ${item.description||item.path?.split(/[\\/]/).pop()||'本地素材'}`));card.append(node('p',`${item.source_id||'未关联来源'}${item.kind==='audio'?'':` · ${item.width||'?'} × ${item.height||'?'}`}${item.duration?' · '+Number(item.duration).toFixed(1)+' 秒':''}`,'small'));if(item.preview_url){const tag=item.kind==='video'?'video':item.kind==='audio'?'audio':'img',preview=node(tag);preview.src=item.preview_url;preview.style.maxWidth='100%';preview.style.maxHeight='280px';if(tag!=='img'){preview.controls=true;preview.preload='none'}else{preview.alt=item.description||'素材预览';preview.loading='lazy'}card.append(preview)}$('assets').append(card)}
  if(spec.bgm?.mode==='media'){const track=media.find(row=>row.id===spec.bgm.media_id),line=node('div',undefined,'notice');line.append(node('span','本片背景音乐：'+(track?.description||track?.name||spec.bgm.media_id)+'。 '),button('取消背景音乐',()=>{spec.bgm={mode:'none'};store();renderAssets();status('已从本次草稿移除背景音乐，请保存后再制作。')}));$('assets').append(line)}
 }
 async function importMedia(){
  try{if(!spec.scenes.length)throw Error('请先生成或添加分镜，再保存项目和导入素材。');await saveProject(false);const data={job_id:jobId,path:$('media-path').value.trim(),kind:$('media-kind').value,description:$('media-description').value.trim()};if($('media-source').value)data.source_id=$('media-source').value;if(!data.path)throw Error('请填写已有素材的绝对路径。');$('media-import').disabled=true;status('正在校验并复制本地素材…');const result=await api('/api/investigation/media',data);media=Array.isArray(result.media)?result.media:[...media,result.item||result.media];$('media-import-panel').hidden=true;renderAssets();renderChapters();store();coverage();status('素材已登记。请在对应镜头中选择这份素材。')}catch(error){status(error.message,true)}finally{$('media-import').disabled=false}
 }
 function safeLibraryPreview(value){try{const url=new URL(value,location.origin);return url.origin===location.origin&&(url.pathname.startsWith('/outputs/')||['/api/library/file','/api/image-references/preview'].includes(url.pathname))?url.href:''}catch{return''}}
 function reusableResource(item){return item&&item.status==='done'&&['image','video','audio'].includes(item.media_type)&&typeof item.absolute_path==='string'&&item.absolute_path.length>0}
 async function resourceItem(id){if(!/^lib-[a-f0-9]{24}$/.test(id))throw Error('资源编号无效。');const {item}=await api('/api/library/item?id='+encodeURIComponent(id));if(item?.id!==id||!reusableResource(item))throw Error('这份资源未完成、已不存在，或不能作为调查素材使用。');return item}
 async function chooseResource(id){try{pendingResource=await resourceItem(id);renderPendingResource();status('资源已待加入，请选择保存目标后点击加入。尚未修改任何工程。');$('library-pending').scrollIntoView({behavior:'smooth',block:'nearest'})}catch(error){status('资源载入失败：'+error.message,true)}}
 async function openResourcePicker(){
  const host=$('library-picker');host.hidden=false;host.replaceChildren(node('p','正在读取可复用资源…','small'));
  try{const results=await Promise.all([api('/api/library?view=assets&status=done'),api('/api/library?view=products&status=done')]),rows=new Map();
   for(const [index,result]of results.entries())for(const item of result.items||[])if(reusableResource(item)&&(index===0||['image','video'].includes(item.media_type)))rows.set(item.id,item);
   host.replaceChildren(node('h3','选择已完成的素材'),node('p','加入时复制到当前项目；来源需在本项目中重新关联。音效仅登记为素材，不会自动循环播放。','small'));
   const search=node('input');search.placeholder='搜索资源名称或工程编号';search.setAttribute('aria-label','搜索可复用资源');host.append(search);const list=node('div',undefined,'grid');host.append(list);
   const draw=()=>{list.replaceChildren();const term=search.value.trim().toLowerCase();for(const item of rows.values()){if(term&&!`${item.title} ${item.project_id||''}`.toLowerCase().includes(term))continue;const card=node('div',undefined,'card');card.append(node('strong',item.title||item.id),node('p',`${item.media_type} · ${item.workflow||item.kind} · ${item.project_id||'资源库'}`,'small'));const preview=safeLibraryPreview(item.thumbnail_url||(item.media_type==='image'?item.preview_url:''));if(preview){const img=node('img');img.src=preview;img.alt=item.title||'资源预览';img.loading='lazy';img.style.maxWidth='100%';img.style.maxHeight='160px';card.append(img)}card.append(button('选择这份资源',()=>chooseResource(item.id),'secondary'));list.append(card)}if(!list.childNodes.length)list.append(node('p','没有匹配的已完成素材。','small'))};search.oninput=draw;draw();
   host.append(button('收起资源库',()=>{host.hidden=true}));
  }catch(error){host.replaceChildren(node('p','无法读取资源库：'+error.message,'error'))}
 }
 function renderPendingResource(){
  const host=$('library-pending');if(!host)return;host.replaceChildren();host.hidden=!pendingResource;if(!pendingResource)return;
  const item=pendingResource;host.append(node('h3','待加入：'+(item.title||item.id)),node('p',`${item.workflow||item.kind} · ${item.project_id||'资源库'}。原工程不会因打开本页而改变。`,'small'));
  const preview=safeLibraryPreview(item.preview_url);if(preview){const tag=item.media_type==='audio'?'audio':item.media_type==='video'?'video':'img',element=node(tag);element.src=preview;element.style.maxWidth='100%';element.style.maxHeight='220px';if(tag==='img'){element.alt=item.title||'待加入素材'}else{element.controls=true;element.preload='none'}host.append(element)}
  const target=node('select');target.id='library-target';target.append(new Option('请选择保存目标',''));if(jobId)target.append(new Option('保存并加入当前工程 '+jobId,'current'));target.append(new Option(jobId?'另存当前分镜为新工程，并复制已有素材':'将当前草稿保存为新工程后加入','new'));host.append(field('加入哪个工程',target));
  host.append(node('p','请先有可保存的分镜。新工程会复制当前分镜和已有素材；新引入资源不继承其他工程的来源 ID。','small'));
  const actions=node('div',undefined,'toolbar');actions.append(button('保存并加入素材',()=>addLibraryResource(false),'secondary'));
  if(item.workflow==='music'&&item.media_type==='audio')actions.append(button('保存并用作背景音乐',()=>addLibraryResource(true),'secondary'));
  if(item.workflow==='sfx')host.append(node('p','这是音效。当前长片尚无逐点音效轨道，本次只能登记素材，不会作为循环背景音乐。','notice'));
  actions.append(button('取消带入',()=>{if(actionBusy)return;pendingResource=null;renderPendingResource()}));host.append(actions);
 }
 async function duplicateProject(){
  const oldJob=jobId,oldMedia=structuredClone(media),copies=[];
  // Resolve all paths from the current allowlisted catalog before creating the new project.
  if(oldMedia.length){const catalog=await api('/api/library?view=assets&status=done');for(const item of oldMedia){const match=(catalog.items||[]).find(row=>row.sha256&&row.sha256===item.sha256&&row.media_type===(item.kind==='evidence'?'image':item.kind));if(!match)throw Error('无法复制已有素材 '+item.id+'，请先在资源库核对该文件。');copies.push({old:item,resource:await resourceItem(match.id)})}}
  backupDraft('另存新工程');jobId=null;
  try{await saveProject(false)}catch(error){jobId=oldJob;projectContext();store();throw error}
  media=[];renderAssets();projectContext();
  for(const copy of copies){const result=await api('/api/investigation/media',{job_id:jobId,path:copy.resource.absolute_path,kind:copy.old.kind,description:copy.old.description||''});media=result.media;for(const scene of spec.scenes)if(scene.media_id===copy.old.id)scene.media_id=result.item.id;if(spec.bgm?.media_id===copy.old.id)spec.bgm.media_id=result.item.id;store()}
  await saveProject(false);renderAssets();renderChapters();
 }
 async function addLibraryResource(asBgm){
  if(actionBusy)return;const target=$('library-target')?.value;if(!pendingResource)return;if(!target)return status('请明确选择当前工程或另存新工程。',true);
  if(!spec.scenes.length)return status('请先添加或载入分镜，再保存并加入这份资源。待加入卡会保留。',true);
  actionBusy=true;for(const control of $('library-pending').querySelectorAll('button,select'))control.disabled=true;
  try{payload();const item=await resourceItem(pendingResource.id);if(asBgm&&(item.workflow!=='music'||item.media_type!=='audio'))throw Error('只有资源库中的配乐可以直接用作背景音乐。');
   if(target==='new'&&jobId)await duplicateProject();else if(target==='current'&&!jobId)throw Error('当前工程已改变，请重新选择保存目标。');else await saveProject(false);
   status('正在复制资源到工程 '+jobId+'…');const kind=item.media_type==='image'&&item.asset_kind==='evidence'?'evidence':item.media_type;
   const result=await api('/api/investigation/media',{job_id:jobId,path:item.absolute_path,kind,description:(item.title||'资源库素材').slice(0,1000)});media=result.media;
   if(asBgm)spec.bgm={...(spec.bgm||{}),mode:'media',media_id:result.item.id};
   await saveProject(false);pendingResource=null;renderAssets();renderChapters();renderPendingResource();coverage();projectContext();store();
   status((asBgm?'已设置背景音乐':'素材已加入')+'：'+jobId+'。'+(asBgm?'重新制作后生效。':'请在镜头中选择素材，并按需要关联本项目来源。'));
  }catch(error){renderAssets();renderChapters();coverage();projectContext();store();status('资源未全部加入：'+error.message+(jobId?'；当前工程 '+jobId+' 已保留已完成的步骤。':''),true)}finally{actionBusy=false;if(pendingResource)renderPendingResource()}
 }
 function previewVoice(){const id=$('voice-preset').value||library.default_preset_id,preset=library.presets.find(item=>item.id===id)||library.references.find(item=>item.path===library.default_voice?.reference);if(!preset?.preview_url){status('当前音色没有可试听的参考录音。',true);return}const audio=$('voice-audio');if(audio.getAttribute('src')!==preset.preview_url)audio.src=preset.preview_url;audio.hidden=false;audio.play().catch(()=>status('请点击播放器开始试听。'))}
 function renderCast(){
  $('characters').replaceChildren();cast.forEach((role,index)=>{const row=node('div',undefined,'role-row'),name=input(role.name,32,()=>{});name.onchange=()=>{const next=name.value.trim();if(!next||next==='旁白'||cast.some((other,i)=>i!==index&&other.name===next)||! /^[\p{L}\p{N} _·-]+$/u.test(next)){name.value=role.name;status('角色名需唯一，仅使用中英文、数字、空格和 _-·。',true);return}const old=role.name;role.name=next;spec.scenes.forEach(scene=>{if(scene.speaker===old)scene.speaker=next});renderChapters();store()};row.append(field('角色名',name),field('音色预设',select(presetOptions('请选择角色音色'),role.preset,value=>{role.preset=value})),button('移除',()=>{cast.splice(index,1);spec.scenes.forEach(scene=>{if(scene.speaker===role.name)scene.speaker='旁白'});renderCast();renderChapters();store()}));$('characters').append(row)});$('add-character').disabled=cast.length>=16;
 }
 function addScene(chapter){if(spec.scenes.length>=96){status('最多 96 个镜头。',true);return}const scene={id:uid('s',spec.scenes),chapter_id:chapter.id,narration:'',speaker:'旁白',kind:'diagram',media_id:null,media_start:0,heading:'',badge:'',text:'',points:[],source_ids:[],fact_status:'needs_review',visual_brief:''};const rank=spec.chapters.indexOf(chapter),next=spec.scenes.findIndex(item=>spec.chapters.findIndex(ch=>ch.id===item.chapter_id)>rank);spec.scenes.splice(next<0?spec.scenes.length:next,0,scene);renderChapters();store()}
 function sceneCard(scene,index,chapterScenes){
  const card=node('details',undefined,'card');card.open=index===0;const summary=node('summary',`${scene.id} · ${scene.heading||'待编辑镜头'} · ${kinds[scene.kind]||'未选素材类型'}`),grid=node('div',undefined,'grid');
  const text=field('旁白 / 台词 · 每段最多 500 字',input(scene.narration,500,value=>{scene.narration=value},'textarea'));text.classList.add('full');text.querySelector('textarea').className='narration';grid.append(text);
  grid.append(field('说话角色',select([['旁白','旁白 · 全片音色'],...cast.map(role=>[role.name,role.name])],scene.speaker||'旁白',value=>{scene.speaker=value})),field('本镜头音色覆盖 · 可选',select(presetOptions('跟随角色 / 全片音色'),scene.voice_preset_id||'',value=>{if(value)scene.voice_preset_id=value;else delete scene.voice_preset_id})),field('画面类型',select(Object.entries(kinds),scene.kind||'diagram',value=>{scene.kind=value;scene.media_id=null;renderChapters()})),field('已登记素材',select([['','图解可留空；证据可用绑定来源的逐字摘录'],...media.filter(item=>scene.kind==='diagram'||item.kind===scene.kind||(scene.kind==='evidence'&&item.kind==='image')).map(item=>[item.id,`${item.id} · ${item.description||item.path?.split(/[\\/]/).pop()||item.kind}`])],scene.media_id||'',value=>{scene.media_id=value||null})),field('视频使用起点 · 秒',numeric(scene.media_start||0,0,86400,value=>{scene.media_start=value},0.1)),field('事实审阅状态',select([['needs_review','待人工核对'],['source_checked','已查阅出处，仍需核对事实'],['user_reviewed','已由我核对来源'],['analysis','解释 / 分析段']],scene.fact_status||'needs_review',value=>{scene.fact_status=value})));
  if(scene.kind==='diagram')grid.append(field('图解布局',select([['flow','流程'],['compare','对比'],['timeline','时间线'],['checklist','检查清单']],scene.diagram_layout||'flow',value=>{scene.diagram_layout=value})));
  grid.append(field('画面短标题',input(scene.heading,80,value=>{scene.heading=value;summary.textContent=`${scene.id} · ${value||'待编辑镜头'} · ${kinds[scene.kind]}`})),field('短标记 · 例如资料画面、日期',input(scene.badge,80,value=>{scene.badge=value})),field('证据摘录 / 说明文字',input(scene.text,1200,value=>{scene.text=value},'textarea')),field('图解要点 · 每行一项，最多 6 项，每项 100 字',input((scene.points||[]).join('\n'),606,value=>{scene.points=value.split('\n').map(item=>item.trim()).filter(Boolean)},'textarea')));
  const sourceSelect=select(spec.sources.map(source=>[source.id,`${source.id} · ${source.title||'未命名来源'}`]),'',()=>{});sourceSelect.multiple=true;sourceSelect.size=Math.min(4,Math.max(2,spec.sources.length));for(const option of sourceSelect.options)option.selected=(scene.source_ids||[]).includes(option.value);sourceSelect.onchange=()=>{scene.source_ids=[...sourceSelect.selectedOptions].map(option=>option.value);store()};grid.append(field('支撑来源 · Ctrl / Command 可多选',sourceSelect),field('画面用途 / 素材缺口',input(scene.visual_brief,1000,value=>{scene.visual_brief=value},'textarea')));
  const toolbar=node('div',undefined,'toolbar');const up=button('向上',()=>{const other=chapterScenes[index-1],a=spec.scenes.indexOf(scene),b=spec.scenes.indexOf(other);[spec.scenes[a],spec.scenes[b]]=[spec.scenes[b],spec.scenes[a]];renderChapters();store()});up.disabled=index===0;const down=button('向下',()=>{const other=chapterScenes[index+1],a=spec.scenes.indexOf(scene),b=spec.scenes.indexOf(other);[spec.scenes[a],spec.scenes[b]]=[spec.scenes[b],spec.scenes[a]];renderChapters();store()});down.disabled=index===chapterScenes.length-1;toolbar.append(up,down,button('移除镜头',()=>{spec.scenes=spec.scenes.filter(item=>item!==scene);renderChapters();coverage();store()}));card.append(summary,grid,toolbar);return card;
 }
 function renderChapters(){
  $('chapters').replaceChildren();if(!spec.chapters.length)$('chapters').append(node('p','先根据资料生成草稿，或载入示例查看完整流程。也可手动添加章节。','empty'));
  spec.chapters.forEach((chapter,index)=>{const box=node('article',undefined,'chapter'),head=node('div',undefined,'header-row'),tools=node('div',undefined,'toolbar');head.append(node('h3',`第 ${index+1} 章 · ${chapter.id}`));tools.append(button('添加镜头',()=>addScene(chapter),'secondary'),button('移除章节',()=>{if(spec.scenes.some(scene=>scene.chapter_id===chapter.id)){status('请先移除该章节内的镜头，再移除章节。',true);return}spec.chapters=spec.chapters.filter(item=>item!==chapter);renderChapters();store()}));head.append(tools);box.append(head);const grid=node('div',undefined,'grid');grid.append(field('章节标题',input(chapter.title,80,value=>{chapter.title=value})),field('本章推进的事实 / 问题',input(chapter.summary,1000,value=>{chapter.summary=value})));box.append(grid);const scenes=spec.scenes.filter(scene=>scene.chapter_id===chapter.id);scenes.forEach((scene,index)=>box.append(sceneCard(scene,index,scenes)));if(!scenes.length)box.append(node('p','本章尚无镜头。','small'));$('chapters').append(box)});$('add-chapter').disabled=spec.chapters.length>=12;
 }
 function payload(){store();if(!spec.title.trim())throw Error('请填写影片标题。');if(!spec.scenes.length)throw Error('请先生成或添加分镜。');for(const role of cast)if(!role.preset)throw Error(`请选择角色「${role.name}」的音色。`);return{...(jobId?{job_id:jobId}:{}),storyboard:spec,...(spec.voice_preset_id?{voice_preset_id:spec.voice_preset_id}:{}),characters:Object.fromEntries(cast.map(role=>[role.name,role.preset]))}}
 async function saveProject(announce=true){const result=await api('/api/investigation/save',payload());jobId=result.job_id;showGaps(result.gaps);showDownloads(result.downloads);projectContext();store();if(announce)status('项目已保存：'+jobId+gapText(result.gaps));return result}
 function showGaps(gaps){const host=$('project-gaps');host.replaceChildren();if(!Array.isArray(gaps)||!gaps.length){host.hidden=true;return}host.hidden=false;host.append(node('summary',`上次保存 / 提交检查：${gaps.length} 项素材或审阅提示`));const list=node('ul');for(const gap of gaps)list.append(node('li',typeof gap==='string'?gap:`${gap.scene_id?gap.scene_id+' · ':''}${gap.message}`));host.append(list);host.open=gaps.some(gap=>gap.severity==='error')}
 function showDownloads(rows){const host=$('project-downloads');host.replaceChildren();for(const row of Array.isArray(rows)?rows:[])if(row.url)host.append(download(row.url,row.label||row.name||'下载文件'))}
 function gapText(gaps){if(!gaps)return'';const values=Array.isArray(gaps)?gaps:Object.values(gaps).flat();return values.length?'；仍有 '+values.length+' 项素材或审阅缺口。':''}
 async function submit(operation){if(actionBusy)return;actionBusy=true;$(operation).disabled=true;try{if(operation==='save'){await saveProject();return}let data;if(operation==='draft'){store();if(!spec.topic.trim())throw Error('请填写具体选题。');data={topic:spec.topic,hot_relevance:spec.hot_relevance,narrative_mode:spec.narrative_mode,mode:spec.mode,target_minutes:spec.target_minutes,sources:spec.sources}}else data=payload();const result=await api('/api/investigation/'+operation,data);if(operation==='draft'){pendingDraft=result.job_id;allowPendingDraft=true}else jobId=result.job_id;store();status('任务已提交：'+result.job_id);await poll()}catch(error){if(error.payload?.job_id){jobId=error.payload.job_id;store()}if(error.payload?.gaps)showGaps(error.payload.gaps);status(error.message,true)}finally{actionBusy=false;$(operation).disabled=false}}
 function download(url,label){const a=node('a',label);a.href=url;a.download='';return a}
 function durationLabel(seconds){const total=Math.max(0,Math.round(seconds));return `${Math.floor(total/60)} 分 ${String(total%60).padStart(2,'0')} 秒`}
 function taskCard(id,state){
  const card=node('article',undefined,'job'),head=node('div',undefined,'header-row');card.dataset.jobId=id;head.append(node('h3',state.title||id),node('span',({queued:'已排队',running:'运行中',done:'已完成',error:'失败',saved:'已保存'})[state.status]||state.status,'tag'));card.append(head,node('p',`${id} · ${state.operation||'项目'}`,'small'),node('p',state.phase||state.status));
  if(Number.isFinite(state.duration_seconds)){const estimated=state.estimated_duration===true||(!state.video&&state.operation==='preview');let detail=`${estimated?'预估时长':'实际时长'}：${durationLabel(state.duration_seconds)}`;if(estimated)detail+=' · 静帧预览按稿件估算，成片以配音实测为准';else{if(state.duration_note)detail+=' · '+state.duration_note;else if(typeof state.target_reached==='boolean')detail+=state.target_reached?' · 达到目标时长':' · 未达到目标时长，需要补充实质内容';if(state.target_difference_seconds<0)detail+=` · 距目标还差 ${durationLabel(-state.target_difference_seconds)}`}card.append(node('p',detail,'notice'))}
  if(['queued','running'].includes(state.status)){const progress=node('progress');if(typeof state.progress==='number'){progress.max=state.progress>1?100:1;progress.value=state.progress}progress.setAttribute('aria-label',state.phase||'任务进行中');card.append(progress)}if(state.error)card.append(node('p',state.error,'error'));
  const toolbar=node('div',undefined,'toolbar');toolbar.append(button('载入此项目',async()=>{try{await loadProject(id)}catch(error){status(error.message,true)}},'secondary'));
  if(state.status==='error')toolbar.append(button('恢复上次任务',async()=>{try{const result=await api('/api/investigation/resume',{job_id:id});status('已请求恢复：'+result.job_id);poll()}catch(error){status(error.message,true)}},'secondary'));card.append(toolbar);
  if(state.video){const video=node('video');video.src=state.video;video.controls=true;video.preload='metadata';card.append(video)}
  if(state.previews?.length){const details=node('details'),grid=node('div',undefined,'preview-grid');details.open=!state.video;details.append(node('summary',`静帧预览 · ${state.previews.length} 张`));for(const url of state.previews){const a=node('a'),img=node('img');a.href=url;a.target='_blank';a.rel='noopener';img.src=url;img.alt='调查长片分镜预览';img.loading='lazy';a.append(img);grid.append(a)}details.append(grid);card.append(details)}
  const links=node('div',undefined,'downloads'),seen=new Set();const add=(url,label)=>{if(typeof url==='string'&&!seen.has(url)){links.append(download(url,label));seen.add(url)}};add(state.video,'下载视频');add(state.subtitle,'下载字幕');add(state.storyboard_url,'源分镜 JSON');add(state.manuscript,'口播稿');add(state.source_ledger,'来源台账');add(state.publish_copy,'发布稿');add(state.bundle,'完整交付包');add(state.verification,'成片检查记录');add(state.manifest_url,'素材与检查清单');(state.covers||[]).forEach((url,index)=>add(url,`封面 ${index+1}`));for(const row of Array.isArray(state.downloads)?state.downloads:[]){add(row.url,row.label||row.name||'下载文件')}if(state.downloads&&!Array.isArray(state.downloads))for(const [label,url]of Object.entries(state.downloads))add(url,label);card.append(links);
  if(state.gaps){const details=node('details');details.append(node('summary','查看素材 / 审阅缺口'));const list=node('ul');for(const gap of Array.isArray(state.gaps)?state.gaps:Object.values(state.gaps).flat())list.append(node('li',typeof gap==='string'?gap:gap.message||JSON.stringify(gap)));details.append(list);card.append(details)}return card;
 }
 async function poll(){if(polling)return;polling=true;try{const data=await api('/api/jobs'),rows=Object.entries(data).filter(([,state])=>state.kind==='investigation').sort((a,b)=>(b[1].created||0)-(a[1].created||0));if(!rows.length){$('jobs').replaceChildren(node('p','暂无调查长片任务。','small'));return}if(!jobNodes.size)$('jobs').replaceChildren();for(const [id,state]of rows){const signature=JSON.stringify(state),old=jobNodes.get(id);if(old?.signature!==signature){const card=taskCard(id,state);if(old)old.node.replaceWith(card);else{const later=rows.slice(rows.findIndex(row=>row[0]===id)+1).find(row=>jobNodes.has(row[0]));$('jobs').insertBefore(card,later?jobNodes.get(later[0]).node:null)}jobNodes.set(id,{signature,node:card})}if(allowPendingDraft&&id===pendingDraft&&state.status==='done'){backupDraft('AI 分章草稿完成');pendingDraft=null;applyProject(await api('/api/investigation/project?job_id='+encodeURIComponent(id)));status('分章草稿已载入，请核对来源并补全素材。')}if(allowPendingDraft&&id===pendingDraft&&state.status==='error'){pendingDraft=null;store();status(state.error||'草稿任务失败，可从下方恢复。',true)}}}catch(error){status('读取任务失败：'+error.message,true)}finally{polling=false}}
 async function loadTopics(){const control=$('topics-load');control.disabled=true;try{status('正在读取公开热榜…');const data=await api('/api/investigation/topics');$('topics').replaceChildren(node('p',`${data.source||'公开热榜'} · 抓取时间 ${data.fetched_at||'未提供'}；热榜只用于选题，不代表报道内容已核实。`,'small'));for(const item of data.items||[]){const row=node('div',undefined,'toolbar');row.append(node('span',item.title),button('带入选题',()=>{$('topic').value=item.title;$('hot-relevance').value=`${data.source||'公开热榜'}，抓取时间 ${data.fetched_at||'未提供'}。原链接：${item.url||''}；事实待核对。`;store();status('已带入选题，请收集原始来源后写稿。')},'secondary'));$('topics').append(row)}status('热榜已读取。请选择有事实入口和素材支持的选题。')}catch(error){status('热榜读取失败：'+error.message,true)}finally{control.disabled=false}}
 function setup(){
  const gaps=node('details',undefined,'notice');gaps.id='project-gaps';gaps.hidden=true;$('coverage').after(gaps);const projectDownloads=node('div',undefined,'downloads');projectDownloads.id='project-downloads';$('environment').before(projectDownloads);
  const demo=node('div',undefined,'notice');demo.id='demo-info';demo.hidden=true;demo.append(node('span','当前为短篇功能演示，不作为目标长片验收。 '),button('转为正式项目',()=>{spec.demo_mode=false;$('target-minutes').value='10';store();$('demo-info').hidden=true;status('已转为正式项目：目标 10 分钟，请补足稿件与真实素材。')},'secondary'));$('coverage').before(demo);
  for(const [id,[label]]of Object.entries(modes))$('narrative-mode').append(new Option(label,id));
  const mode=select([['investigation','调查长片 · 真实视频承担叙事'],['explainer','机制讲解 · 可使用图解为主']],'investigation',value=>{spec.mode=value});mode.id='production-mode';$('narrative-mode').parentElement.after(field('内容方式',mode));
  const topics=node('div');topics.id='topics';const topicsButton=button('读取公开热榜',loadTopics,'secondary');topicsButton.id='topics-load';$('topic').parentElement.before(topicsButton,topics);
  const importPanel=node('div',undefined,'card');importPanel.id='media-import-panel';importPanel.hidden=true;const grid=node('div',undefined,'grid');const path=input('',null,()=>{});path.id='media-path';path.placeholder='例如 D:\\素材\\事件原片.mp4';const kind=select([...Object.entries(kinds).filter(([id])=>id!=='diagram'),['audio','音频素材']],'video',()=>{});kind.id='media-kind';const source=select(knownSourceOptions(),'',()=>{});source.id='media-source';const description=input('',300,()=>{});description.id='media-description';grid.append(field('本机文件完整路径',path),field('素材类型',kind),field('来源关联',source),field('素材内容说明',description));const importButton=button('校验并导入素材',importMedia,'secondary');importButton.id='media-import';importPanel.append(grid,importButton);$('assets').before(importPanel);
  const picker=node('div',undefined,'card');picker.id='library-picker';picker.hidden=true;const pending=node('div',undefined,'notice');pending.id='library-pending';pending.hidden=true;$('assets').before(pending,picker);$('add-asset').after(button('从资源库选择',openResourcePicker,'secondary'));
  $('add-asset').onclick=()=>{$('media-source').replaceChildren(...knownSourceOptions().map(([id,label])=>new Option(label,id)));importPanel.hidden=false;$('media-path').focus()};
  for(const id of ['topic','hot-relevance','target-minutes','project-title'])$(id).addEventListener('input',store);$('narrative-mode').onchange=()=>{$('narrative-help').textContent=modes[$('narrative-mode').value][1];store()};$('voice-preset').onchange=store;$('voice-preview').onclick=previewVoice;
  $('add-source').onclick=()=>{if(spec.sources.length>=24)return;spec.sources.push({id:uid('src',spec.sources),title:'',url:'',published_at:'',content:'',status:'unreviewed'});renderSources();renderChapters();store()};
  $('add-chapter').onclick=()=>{if(spec.chapters.length>=12)return;spec.chapters.push({id:uid('ch',spec.chapters),title:'新章节',summary:''});renderChapters();store()};
  $('add-character').onclick=()=>{if(cast.length>=16)return;let index=cast.length+1;while(cast.some(role=>role.name===`角色${index}`))index++;cast.push({name:`角色${index}`,preset:$('voice-preset').value||library.default_preset_id||library.presets[0]?.id||''});renderCast();renderChapters();store()};
  for(const operation of ['draft','save','preview','render'])$(operation).onclick=()=>submit(operation);$('refresh').onclick=poll;
  $('example').onclick=async()=>{try{applyProject(await api('/api/investigation/example'));status('已载入短篇功能示例，用于体验流程；不是 10 分钟热点调查成片。')}catch(error){status(error.message,true)}};
  $('export').onclick=()=>{try{store();const blob=new Blob([JSON.stringify(spec,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=download(url,'');link.download='investigation-storyboard.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(error){status(error.message,true)}};
  $('import').onchange=async()=>{try{const file=$('import').files[0];if(!file)return;if(file.size>500000)throw Error('项目 JSON 应小于 500 KB。');applyProject(JSON.parse(await file.text()));status('JSON 已载入为新的编辑项目；素材需要重新登记。')}catch(error){status(error.message,true)}finally{$('import').value=''}};
 }
 async function init(){setup();const params=new URLSearchParams(location.search);allowPendingDraft=!params.has('project')&&!params.has('resource');try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(saved?.storyboard){pendingDraft=saved.pendingDraft||null;applyProject({...saved,job_id:saved.jobId})}else renderAll()}catch{renderAll();status('上次草稿无法读取，可以导入项目 JSON 或载入示例。',true)}
  try{library=await api('/api/voice-library');renderAll()}catch(error){status('音色库读取失败：'+error.message,true)}
  try{const health=await api('/api/investigation/health');$('environment').textContent=(health.ready?'制作环境已就绪。':'制作环境仍需配置。')+' '+(health.message||(health.checks||[]).filter(check=>!check.ready).map(check=>check.name+'：'+check.message).join('；'))}catch(error){$('environment').textContent='无法读取制作环境：'+error.message}
  try{const service=await api('/api/services');$('services').textContent=`千问生图：${service.comfyui.ready?'就绪':'未启动'} · 配音：${service.tts.ready?'就绪':'未启动'}`}catch{}
  if(params.has('project')){try{await loadProject(params.get('project'))}catch(error){status('无法载入指定工程：'+error.message,true)}}
  if(params.has('resource'))await chooseResource(params.get('resource'));
  poll();setInterval(poll,3000);
 }
 init();
})();
