(async()=>{
const $=id=>document.getElementById(id),api=Creation.api,storageKey='ai-studio-novel-v1';let draft={title:'新小说漫剧',scenes:[],characters:{}},currentJob=null,lastJobs='';
await Creation.ready;await Director.ready;
const methodPicker=Director.methodSelect($('director-method-box'),sessionStorage.getItem('director-method')||'');sessionStorage.removeItem('director-method');
const localStatus=document.createElement('p');localStatus.className='small';localStatus.textContent='正在检查本地编剧模型…';$('adapt').after(localStatus);
try{const state=await api('/api/story/status');localStatus.textContent=state.message;if(state.ready){$('adapt-mode').value='local';$('adapt-mode').querySelector('option[value="local"]').textContent='本地 AI 编剧 · '+state.model}}catch(e){localStatus.textContent='编剧服务检查失败：'+e.message}

const emotionOptions=()=>Creation.inventory.emotions.map(x=>[x,x]);
const voiceOptions=()=>Creation.inventory.voices.map(v=>[v.path,v.name]);
function status(t){$('novel-status').textContent=t}
function input(label,value,type='text'){const l=document.createElement('label');l.textContent=label;const e=document.createElement(type==='textarea'?'textarea':'input');if(type!=='textarea')e.type=type;e.value=value||'';l.append(e);return [l,e]}
function renderCharacters(){const box=$('characters');box.replaceChildren();for(const [name,v]of Object.entries(draft.characters)){const row=document.createElement('div');row.className='control-group';const h=document.createElement('h3');h.textContent=name;row.append(h);const grid=document.createElement('div');grid.className='control-grid';
 for(const [key,label]of [['reference','本地音色'],['emotion','本地情感'],['intensity','情感强度'],['speed','语速'],['online_voice','在线音色 ID']]){const l=document.createElement('label');l.textContent=label;let e;if(key==='reference')e=Creation.select(voiceOptions(),v[key]);else if(key==='emotion')e=Creation.select(emotionOptions(),v[key]);else{e=document.createElement('input');e.type=['speed','intensity'].includes(key)?'number':'text';e.value=v[key];if(e.type==='number'){e.step=.05;e.min=key==='speed'?.5:0;e.max=key==='speed'?2:.8}}e.setAttribute('aria-label',name+' '+label);e.onchange=()=>v[key]=e.type==='number'?Number(e.value):e.value;l.append(e);grid.append(l)}row.append(grid);box.append(row)}}
function renderScenes(){const box=$('scenes');box.replaceChildren();draft.scenes.forEach((s,index)=>{const card=document.createElement('article');card.className='scene-card';const head=document.createElement('div');head.className='scene-actions';const title=document.createElement('strong');title.textContent=`镜头 ${index+1}`;head.append(title);
 for(const [text,action]of [['上移',()=>{if(index){[draft.scenes[index-1],draft.scenes[index]]=[s,draft.scenes[index-1]];renderScenes()}}],['下移',()=>{if(index<draft.scenes.length-1){[draft.scenes[index+1],draft.scenes[index]]=[s,draft.scenes[index+1]];renderScenes()}}],['移除',()=>{draft.scenes.splice(index,1);renderScenes()}]]){const b=document.createElement('button');b.textContent=text;b.className='secondary';b.onclick=action;head.append(b)}card.append(head);
 const speakerLabel=document.createElement('label');speakerLabel.textContent='说话角色';const speaker=Creation.select(Object.keys(draft.characters).map(x=>[x,x]),s.speaker||'旁白');speaker.setAttribute('aria-label',`镜头 ${index+1} 说话角色`);speaker.onchange=()=>s.speaker=speaker.value;speakerLabel.append(speaker);card.append(speakerLabel);
 for(const [key,label,type]of [['narration','旁白 / 台词','textarea'],['subject','画面描述（人物外貌、动作、场景）','textarea'],['style','画风','text'],['motion_prompt','动作与运镜','textarea']]){const [l,e]=input(label,s[key],type);e.setAttribute('aria-label',`镜头 ${index+1} ${label}`);e.oninput=()=>s[key]=e.value;card.append(l)}Director.mountScene(card,s,(prompt,plan)=>{s.motion_prompt=prompt;s.camera_plan=plan;renderScenes()});box.append(card)});$('scene-count').textContent=`${draft.scenes.length} / 12 个镜头 · 请核对原文、画面和角色，再提交生成`}
function defaultCharacters(){if(!draft.characters||!Object.keys(draft.characters).length)draft.characters={'旁白':{...Creation.read().voice}};for(const s of draft.scenes){s.speaker=s.speaker||'旁白';if(!draft.characters[s.speaker])draft.characters[s.speaker]={...Creation.read().voice}}}
function accept(d){draft=d;methodPicker.value=d.director_method||'';methodPicker.dispatchEvent(new Event('change'));defaultCharacters();$('novel-title').value=d.title||'新小说漫剧';$('novel-text').value=d.source_text||'';if(d.settings)Creation.set(d.settings);if(d.backends)for(const [k,v]of Object.entries(d.backends))if($('use-'+k))$('use-'+k).value=v;$('novel-motion').checked=!!d.motion_enabled;renderCharacters();renderScenes();status(d.draft_method||'草稿已载入')}
function collect(){draft.director_method=methodPicker.value;draft.title=$('novel-title').value;draft.source_text=$('novel-text').value;draft.settings=Creation.read();draft.backends=Object.fromEntries(['tts','asr','image','video'].map(k=>[k,$('use-'+k).value]));draft.motion_enabled=$('novel-motion').checked;draft.render_mode='illustrated';draft.scenes.forEach((s,i)=>{s.id=`scene${String(i+1).padStart(2,'0')}`});return draft}
function remember(){try{localStorage.setItem(storageKey,JSON.stringify(collect()))}catch{}}
function backupDraft(reason){
 const snapshot={saved_at:new Date().toISOString(),reason,draft:structuredClone(collect())};let rows=[];try{rows=JSON.parse(localStorage.getItem(storageKey+'-backups')||'[]')}catch{}if(!Array.isArray(rows))rows=[];
 try{localStorage.setItem(storageKey+'-backups',JSON.stringify([...rows.slice(-4),snapshot]))}catch{throw Error('浏览器无法备份当前草稿，已停止替换。请先保存草稿或释放浏览器存储。')}
 let host=$('novel-draft-backup');if(!host){host=document.createElement('p');host.id='novel-draft-backup';host.className='small';$('novel-status').after(host)}host.textContent='载入前的浏览器草稿已备份。 ';const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent='下载备份';button.onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot.draft,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='novel-before-load.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};host.append(button);
}
function checkDraft(value){if(!value||!Array.isArray(value.scenes)||value.scenes.some(scene=>!scene||typeof scene.narration!=='string'))throw Error('指定草稿没有有效的小说分镜。');return structuredClone(value)}
async function loadLibraryDraft(id){
 if(!/^lib-[a-f0-9]{24}$/.test(id))throw Error('草稿资源编号无效。');const {item}=await api('/api/library/item?id='+encodeURIComponent(id));
 if(item?.id!==id||item.workflow!=='story'||!/^[a-f0-9]{12}$/.test(item.draft_id||''))throw Error('指定资源不是已保存的小说草稿。');
 const url=new URL(item.download_url,location.origin);if(url.origin!==location.origin||url.pathname!=='/api/library/file'||url.searchParams.get('id')!==id||url.hash)throw Error('草稿文件地址无效。');
 const value=checkDraft(await api(url.pathname+url.search));backupDraft('载入小说草稿 '+item.draft_id);accept(value);currentJob=null;remember();$('draft-list').value=item.draft_id;
 const main=document.querySelector('main');if(main)main.dataset.currentProject=item.project_id||('draft-'+item.draft_id);
 status('已载入指定小说草稿 '+item.draft_id+'：'+(value.title||'未命名')+'。原浏览器草稿已备份；尚未提交制作。');
}
$('novel-file').onchange=async()=>{try{const f=$('novel-file').files[0];if(!f)return;if(f.size>200000)throw Error('请按章节导入小于 200 KB 的 UTF-8 TXT');$('novel-text').value=await f.text();status('已导入文本。请选择本次制作片段（最多 16000 字）。')}catch(e){status(e.message)}};
$('adapt').onclick=async()=>{const b=$('adapt');try{b.disabled=true;status('正在生成分镜草稿…');const data=await api('/api/novel',{text:$('novel-text').value,title:$('novel-title').value,mode:$('adapt-mode').value,count:Number($('scene-limit').value),style:$('novel-style').value,director_method:methodPicker.value});if(data.job_id){currentJob=data.job_id;status('编剧任务已提交：'+currentJob)}else accept({...data,characters:draft.characters})}catch(e){status(e.message)}finally{b.disabled=false}};
$('add-character').onclick=()=>{const name=$('character-name').value.trim();if(!name)return;if(draft.characters[name]){status('角色已存在');return}draft.characters[name]={...Creation.read().voice};$('character-name').value='';renderCharacters();renderScenes()};
$('add-scene').onclick=()=>{if(draft.scenes.length>=12){status('本批最多 12 镜头，请分章节制作');return}draft.scenes.push({id:'new',speaker:'旁白',narration:'',subject:'',style:$('novel-style').value,motion_prompt:'缓慢推近，保持人物与场景一致。'});renderScenes()};
$('save-draft').onclick=async()=>{try{const r=await api('/api/drafts',collect());status(r.message+'：'+r.id);await listDrafts();$('draft-list').value=r.id}catch(e){status(e.message)}};
async function listDrafts(){const rows=await api('/api/drafts');$('draft-list').replaceChildren(new Option('选择已保存草稿',''));for(const row of rows)$('draft-list').append(new Option(row.title+' · '+row.id,row.id))}
$('load-draft').onclick=async()=>{try{if($('draft-list').value){const value=checkDraft(await api('/api/drafts/'+$('draft-list').value));backupDraft('载入已保存草稿 '+$('draft-list').value);accept(value);remember()}}catch(e){status(e.message)}};
$('make-novel').onclick=async()=>{const b=$('make-novel');try{b.disabled=true;const r=await api('/api/produce',{storyboard:collect()});status('制作任务已提交：'+r.job_id+'；页面下方可查看进度和成片。');poll()}catch(e){status(e.message)}finally{b.disabled=false}};
async function poll(){try{const jobs=await api('/api/jobs');if(currentJob){const j=jobs[currentJob];if(j?.status==='done'){accept({...j.storyboard,characters:draft.characters});currentJob=null}else if(j?.status==='error'){status(j.error);currentJob=null}}const signature=JSON.stringify(Object.entries(jobs).filter(([,j])=>j.kind==='video'));if(signature===lastJobs)return;lastJobs=signature;const box=$('novel-jobs');box.replaceChildren();for(const [id,j]of Object.entries(jobs).reverse()){if(j.kind!=='video')continue;const p=document.createElement('p');p.textContent=id+' · '+j.status+(j.error?' · '+j.error:'');box.append(p);if(j.video){const video=document.createElement('video');video.controls=true;video.preload='metadata';video.src=j.video;box.append(video)}}}catch(e){status(e.message)}}
document.addEventListener('voices-updated',renderCharacters);defaultCharacters();renderCharacters();renderScenes();
try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(saved)accept(checkDraft(saved))}catch(e){status('上次浏览器草稿无法读取：'+e.message)}
await listDrafts();const requested=new URLSearchParams(location.search).get('draft');if(requested!==null){try{await loadLibraryDraft(requested)}catch(e){status('无法载入指定小说草稿：'+e.message)}}
document.addEventListener('input',remember);document.addEventListener('change',remember);window.addEventListener('pagehide',remember);poll();setInterval(poll,7000);
})().catch(e=>document.getElementById('novel-status').textContent=e.message);
