(()=>{
 'use strict';
 const $=id=>document.getElementById(id);let library={presets:[],references:[],emotions:[]},editingId=null,editingVoice={},fixedJob=null;
 const qwenSpeakers=['Vivian','Serena','Uncle_Fu','Dylan','Eric','Ryan','Aiden','Ono_Anna','Sohee'];
 const qwenLanguages=[['Chinese','中文'],['English','英语'],['Japanese','日语'],['Korean','韩语'],['German','德语'],['French','法语'],['Russian','俄语'],['Portuguese','葡萄牙语'],['Spanish','西班牙语'],['Italian','意大利语'],['Auto','自动识别']];
 const node=(tag,text,className)=>{const item=document.createElement(tag);if(text!==undefined)item.textContent=text;if(className)item.className=className;return item};
 function status(text,error=false){$('library-status').textContent=text;$('library-status').className='status'+(error?' error':'')}
 async function api(url,data){const response=await fetch(url,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'请求失败');return result}
 function action(label,callback,className='secondary'){const button=node('button',label,className);button.type='button';button.onclick=callback;return button}
 function link(label,url){const anchor=node('a',label,'button secondary');anchor.href=url;return anchor}
 function play(name,url){if(!url){status('该音色暂时没有可试听的参考录音。',true);return}const audio=$('reference-audio');if(audio.getAttribute('src')!==url)audio.src=url;$('playing-name').textContent=name;$('reference-player').hidden=false;audio.play().catch(()=>status('请点击播放器开始试听。'))}
 function render(){
  const query=$('voice-search').value.trim().toLowerCase(),tag=$('voice-tag').value;
  const presets=library.presets.filter(preset=>(!tag||(preset.tags||[]).includes(tag))&&(!query||[preset.name,preset.description,...(preset.tags||[])].join(' ').toLowerCase().includes(query)));
  $('voice-list').replaceChildren();if(!presets.length){$('voice-list').append(node('p','没有符合条件的音色，可以清空筛选或新建预设。','empty'));return}
  for(const preset of presets){
   const card=node('article',undefined,'voice-card'),tags=node('div',undefined,'tag-list');card.append(node('h3',preset.name));
   if(preset.id===library.default_preset_id)tags.append(node('span','默认音色','tag default'));
   for(const tag of preset.tags||[])tags.append(node('span',tag,'tag'));if(tags.childNodes.length)card.append(tags);
   card.append(node('p',preset.description||'尚未填写适用说明。','small'));
   const voice=preset.voice||{},expression=voice.engine==='qwen3-clone'?'Qwen3-TTS · 固定参考克隆':voice.engine==='qwen3-design'?'Qwen3-TTS · 声音设计，需先固定为克隆参考':voice.engine==='qwen3-custom'?`Qwen3-TTS · ${voice.qwen_speaker||'Vivian'} · ${voice.qwen_instruct||'默认表达'}`:voice.prosody_reference?`IndexTTS · 表达参考：${library.references.find(item=>item.path===voice.prosody_reference)?.name||'已选录音'} · 强度 ${voice.prosody_strength??1}`:`IndexTTS · ${voice.emotion||'平静'} · 强度 ${voice.intensity??0}`;card.append(node('p',`${expression} · 语速 ${voice.speed??1} ×`,'small'));
   if(preset.source==='builtin')card.append(node('p','内置参考 · 听感待试听','small'));
   const toolbar=node('div',undefined,'toolbar');toolbar.append(action('参考试听',()=>play(preset.name,preset.preview_url)),link('试配音',`/speech?preset=${encodeURIComponent(preset.id)}`),link('用于白板',`/whiteboard?preset=${encodeURIComponent(preset.id)}`));
   toolbar.append(action('设为默认',async()=>{try{const result=await api('/api/voice-library/default',{id:preset.id});status(result.message||'已设为默认音色，新任务会使用。');await load()}catch(error){status(error.message,true)}},'quiet'),action(preset.source==='saved'?'编辑预设':'另存预设',()=>edit(preset),'quiet'));card.append(toolbar);$('voice-list').append(card);
  }
 }
 async function load(){library=await api('/api/voice-library');const current=$('voice-tag').value;$('voice-tag').replaceChildren(new Option('全部题材',''));for(const tag of [...new Set(library.presets.flatMap(preset=>preset.tags||[]))].sort())$('voice-tag').append(new Option(tag,tag));if([...$('voice-tag').options].some(option=>option.value===current))$('voice-tag').value=current;render()}
 function edit(preset=null,voiceOverride=null){
  editingId=preset?.source==='saved'?preset.id:null;
  const defaults=library.default_voice||library.presets.find(item=>item.id===library.default_preset_id)?.voice||library.presets[0]?.voice||{};
  const voice=voiceOverride||preset?.voice||defaults;
  editingVoice=structuredClone(voice);
  $('preset-engine').value=voice.engine||'index-tts';$('preset-qwen-speaker').replaceChildren(...qwenSpeakers.map(name=>new Option(name,name)));$('preset-qwen-speaker').value=voice.qwen_speaker||'Vivian';$('preset-qwen-language').replaceChildren(...qwenLanguages.map(([value,label])=>new Option(label,value)));$('preset-qwen-language').value=voice.qwen_language||'Chinese';$('preset-qwen-instruct').value=voice.qwen_instruct||'';$('preset-qwen-reftext').value=voice.qwen_ref_text||'';$('preset-qwen-seed').value=voice.qwen_seed??42;
  $('preset-editor-title').textContent=editingId?'编辑音色预设':'保存新的音色预设';$('preset-name').value=preset?(editingId?preset.name:preset.name+' · 自定义'):'';$('preset-tags').value=(preset?.tags||[]).join('，');$('preset-description').value=preset?.description||'';
  $('preset-reference').replaceChildren(new Option('请选择参考声音',''));for(const reference of library.references)$('preset-reference').append(new Option(reference.name,reference.path));$('preset-reference').value=voice.reference||'';
  $('preset-emotion').replaceChildren();for(const emotion of library.emotions)$('preset-emotion').append(new Option(emotion,emotion));$('preset-emotion').value=voice.emotion||'平静';$('preset-intensity').value=voice.intensity??0.6;$('preset-speed').value=voice.speed??1;$('preset-online').value=voice.online_voice||'alloy';
  $('preset-duration').value=voice.duration_factor??1;$('preset-pitch').value=voice.pitch_semitones??0;$('preset-formant').value=voice.formant_shift??1;
  $('preset-prosody').replaceChildren(new Option('按情感控制',''));for(const reference of library.references)$('preset-prosody').append(new Option(reference.name,reference.path));if(voice.prosody_reference&&!library.references.some(reference=>reference.path===voice.prosody_reference))$('preset-prosody').append(new Option('原表达参考（需要重新登记）',voice.prosody_reference));$('preset-prosody').value=voice.prosody_reference||'';$('preset-prosody-strength').value=voice.prosody_strength??1;updateExpressionMode();
  $('preset-editor').hidden=false;$('preset-editor').scrollIntoView({behavior:'smooth',block:'start'});$('preset-name').focus();
 }
 function updateExpressionMode(){const engine=$('preset-engine').value,qwen=engine.startsWith('qwen3-'),design=engine==='qwen3-design',usingReference=!!$('preset-prosody').value;$('preset-emotion').disabled=qwen||usingReference;$('preset-intensity').disabled=qwen||usingReference;$('preset-prosody-strength').disabled=qwen||!usingReference;for(const item of document.querySelectorAll('[data-voice-engine]'))item.hidden=!item.dataset.voiceEngine.split(' ').includes(engine);$('preset-reference').closest('label').hidden=['qwen3-custom','qwen3-design'].includes(engine);$('preset-reference').required=!['qwen3-custom','qwen3-design'].includes(engine);$('preset-preview').hidden=design||(engine==='qwen3-custom'&&(editingVoice.engine!=='qwen3-custom'||!editingVoice.reference));$('preset-name').required=!design;$('save-preset').textContent=design?'先生成试听，再保存固定角色':'保存到音色库';$('preset-engine-note').textContent=({'index-tts':'IndexTTS 使用参考声音克隆音色，可通过情感或独立表达参考控制语气。','qwen3-custom':'Qwen 使用现成声线和表达要求生成声音；参考录音仅供试听，不参与克隆。','qwen3-design':'声音设计需先生成试听，再把满意结果保存为固定克隆参考。不会直接保存为每镜头重新设计的角色预设。','qwen3-clone':'Qwen 根据参考录音克隆声音。原文可留空，仅提取音色向量；填写与录音一致的原文可提供更多克隆信息。此模式不使用表达描述。'})[engine]||'';$('preset-engine-health').hidden=!qwen;if(qwen)checkQwen(engine);updateProcessingSummary(true)}
 const qwenChecks=new Map();
 function updateProcessingSummary(reveal=false){const speed=Number($('preset-speed').value),pitch=Number($('preset-pitch').value),formant=Number($('preset-formant').value),active=speed!==1||pitch!==0||formant!==1;let panel=$('preset-processing');if(!panel){panel=node('div',undefined,'full');panel.id='preset-processing';const summary=node('p',undefined,'small'),reset=action('将语速、音高、共鸣设为原值',()=>{$('preset-speed').value=1;$('preset-pitch').value=0;$('preset-formant').value=1;updateProcessingSummary()});panel.append(summary,reset);$('preset-engine-note').after(panel)}panel.querySelector('p').textContent=`${active?'后期调音已启用':'不作语速、音高或共鸣变声'}：语速 ${speed} × · 音高 ${pitch} 半音 · 共鸣 ${formant}。`;panel.querySelector('button').hidden=!active;if(active&&reveal)$('preset-pitch').closest('details').open=true}
 for(const id of ['preset-speed','preset-pitch','preset-formant'])$(id).addEventListener('input',()=>updateProcessingSummary());
 async function checkQwen(engine){const hint=$('preset-engine-health');hint.textContent='正在检查所选 Qwen3-TTS 本地模型…';try{if(!qwenChecks.has(engine))qwenChecks.set(engine,api('/api/voice-library/qwen-status?engine='+encodeURIComponent(engine)));const result=await qwenChecks.get(engine);if($('preset-engine').value!==engine)return;hint.textContent=(result.ready?'本地文件检查通过；首次试配音仍需验证。':'所选 Qwen3-TTS 模型尚未就绪。')+' '+(result.checks||[]).filter(row=>!row.ready).map(row=>row.message).join(' ');hint.className='small full'+(result.ready?'':' error')}catch(error){qwenChecks.delete(engine);if($('preset-engine').value!==engine)return;hint.textContent='暂时无法检查 Qwen3-TTS：'+error.message+'。配音时会明确检查，不会自动切换引擎。';hint.className='small full error'}}
 $('preset-prosody').onchange=updateExpressionMode;
 $('preset-engine').onchange=updateExpressionMode;
 $('preset-form').onsubmit=async event=>{event.preventDefault();$('save-preset').disabled=true;try{const voice={...editingVoice,reference:['qwen3-custom','qwen3-design'].includes($('preset-engine').value)?($('preset-engine').value==='qwen3-custom'&&editingVoice.engine==='qwen3-custom'?editingVoice.reference||'':''):$('preset-reference').value,emotion:$('preset-emotion').value,intensity:Number($('preset-intensity').value),speed:Number($('preset-speed').value),online_voice:$('preset-online').value.trim(),duration_factor:Number($('preset-duration').value),pitch_semitones:Number($('preset-pitch').value),formant_shift:Number($('preset-formant').value),prosody_reference:$('preset-prosody').value,prosody_strength:Number($('preset-prosody-strength').value),engine:$('preset-engine').value,qwen_speaker:$('preset-qwen-speaker').value,qwen_instruct:$('preset-qwen-instruct').value.trim(),qwen_language:$('preset-qwen-language').value,qwen_seed:Number($('preset-qwen-seed').value),qwen_ref_text:$('preset-qwen-reftext').value.trim()};if(voice.engine==='qwen3-design'){sessionStorage.setItem('voice-library-to-speech',JSON.stringify(voice));location.assign('/speech?engine=qwen3-design');return}const data={name:$('preset-name').value.trim(),tags:$('preset-tags').value.split(/[,，、]/).map(tag=>tag.trim()).filter(Boolean),description:$('preset-description').value.replace(/[\r\n]+/g,' ').trim(),voice};if(editingId)data.id=editingId;const result=await api('/api/voice-library/save',data);status(result.message||'音色预设已保存。');await load();$('preset-editor').hidden=true}catch(error){status(error.message,true)}finally{$('save-preset').disabled=false}};
 $('preset-preview').onclick=()=>{const reference=library.references.find(item=>item.path===$('preset-reference').value);if(reference)play(reference.name,reference.preview_url)};
 $('voice-search').addEventListener('input',render);$('voice-tag').onchange=render;$('new-preset').onclick=()=>edit();$('cancel-preset').onclick=()=>{$('preset-editor').hidden=true};
 async function showFixedJob(id){const jobs=await api('/api/jobs'),job=jobs[id];if(!job||job.kind!=='speech'||job.status!=='done'||!job.audio)throw Error('该配音任务尚未成功，无法保存为角色音色。');if(job.voice_engine!=='qwen3-design')throw Error('此入口仅保存已成功生成的 Qwen 声音设计。');fixedJob=id;$('fixed-voice-job').textContent='来源任务：'+id;$('fixed-voice-audio').src=job.audio;$('fixed-voice-editor').hidden=false;$('fixed-voice-editor').scrollIntoView({behavior:'smooth',block:'start'});$('fixed-voice-name').focus();status('先试听这次结果，再填写角色名称保存。')}
 $('fixed-voice-form').onsubmit=async event=>{event.preventDefault();if(!fixedJob)return;$('fixed-voice-save').disabled=true;try{const result=await api('/api/voice-library/from-speech',{job_id:fixedJob,name:$('fixed-voice-name').value.trim(),tags:$('fixed-voice-tags').value.split(/[,，、]/).map(tag=>tag.trim()).filter(Boolean),description:$('fixed-voice-description').value.replace(/[\r\n]+/g,' ').trim()});status(result.message||'已保存为固定角色音色。');$('fixed-voice-editor').hidden=true;await load();history.replaceState(null,'','/voices')}catch(error){status(error.message,true)}finally{$('fixed-voice-save').disabled=false}};
 async function init(){try{await load();const query=new URLSearchParams(location.search);if(query.get('fromJob'))await showFixedJob(query.get('fromJob'));else if(query.get('from')==='speech'){let saved=null;try{saved=JSON.parse(sessionStorage.getItem('voice-library-from-speech')||'null')}catch{}if(saved){edit(null,saved);status(saved.engine==='qwen3-design'?'已带入声音设计参数。请先生成试听，再从成功任务保存固定角色。':'已带入配音页当前参数。填写名称和题材后保存。')}else status('未找到配音页参数，可直接选择参考声音新建预设。')}}catch(error){status(error.message,true);if(!library.presets.length)$('voice-list').replaceChildren(node('p','音色库暂时无法读取，请稍后刷新。','empty'))}try{const services=await api('/api/services');$('services').textContent=`千问生图：${services.comfyui.ready?'就绪':'未启动'} · 配音：${services.tts.ready?'就绪':'未启动'}`}catch{}}
 init();
})();
